.travis.yml
We would need the docker login only when we push the container images to
our public respoitories. This event would happen only during a release
which should never be performed from a forked repository.
Moving the `docker login` to the deploy stage would thus ensure that the
encrypted environment variables are never accessed from a forked repo.
=> Moved the docker login to `deploy` stage.

docs/tutorial.md, pkg/appgw/appgw_test.go
Fix the following typos found by misspell:
```
docs/tutorial.md:118:59: "availble" is a misspelling of "available"
pkg/appgw/appgw_test.go:251:21: "listners" is a misspelling of "listeners"
```
=> Fix 2 typos in documentation and comment

.gitattributes, CMakeLists.txt, pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go
`docker-push` didn't have a dependency on the `dockerize` target because of which it was not building the deployment image before pushing it to the registry. Introduced the dependency to make `docker-push` work.
=> Fix docker push

.travis.yml, scripts/deploy.sh
The script provider in deploy stage apparently needs to be a scalar and hence cannot take multiple commands. We therefore need to setup the `docker login` in a stage before the deploy begins.
=> Fixed deploy stage for travis-CI.

pkg/appgw/httpListeners.go
We were creating HTTP listeners for ingress spec that had TLS specified. Modifed the listener creation to create HTTP listeners only if the TLS spec is not specified.
=> Modified creation of HTTP listener.

.gitignore
Adding `.idea/` and `*~` to `.gitignore`.
These are directory and files created by Intellij/Goland and Emacs respectively.
=> Ignore more files created by text editors

.gitignore
Ignore file names containing `#`. These are typically  backup (autosave) files created by Emacs. (For instance: `#azure-pipelines.yml#`)
=> gitignore: Ignore Emacs autosave files

pkg/k8scontext/context.go, pkg/k8scontext/secretstore.go
Carving out a small piece of a [larger PR](https://github.com/Azure/application-gateway-kubernetes-ingress/pull/132/files) here to make the changes more palatable.
The goal of this change is to make the struct exportable and reusable within other packages. Also this brings the interface naming a bit closer to the ` 'er' appended to it` [idea](https://talks.golang.org/2014/names.slide#13).
=> k8scontext: Rename interface to SecretsKeeper; struct to SecretsStore

pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go
In this PR we introduce `IsSslRedirect`, which at this point is unused. This is a small chunk of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/132
The goal of this small PR is to reduce the noise in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/132 -- surface the actual changes that need to be carefully reviewed.
The added unit test will **not** be executed w/ the current CMake targets.
PR https://github.com/Azure/application-gateway-kubernetes-ingress/pull/141 introduces a change, which will execute all tests.
Will merge https://github.com/Azure/application-gateway-kubernetes-ingress/pull/141 first, then test the PR here w/ the new CMake and then merge.
=> annotations: Adding IsSslRedirect function

CMakeLists.txt
Reading [the ginkgo documentation](https://onsi.github.io/ginkgo/) it turns out we can generalize running the tests w/ `go tests`
This allows for generic Go tests to be executed as well. (Generic go tests come w/ https://github.com/Azure/application-gateway-kubernetes-ingress/pull/132)
```
$ ginkgo ./...
[1556908432] Appgw Suite - 4/4 specs I0503 11:34:01.287623   30971 context.go:287] k8s context run started
I0503 11:34:01.287934   30971 context.go:374] start waiting for initial cache sync
I0503 11:34:01.489000   30971 context.go:389] ingress initial sync done
I0503 11:34:01.489029   30971 context.go:289] k8s context run finished
•I0503 11:34:01.489426   30971 context.go:287] k8s context run started
I0503 11:34:01.489442   30971 context.go:374] start waiting for initial cache sync
I0503 …
```
=> cmake: Combine Go test targets; Test all packages

pkg/appgw/internaltypes.go, pkg/appgw/internaltypes_test.go
A tiny piece of a larger PR - https://github.com/Azure/application-gateway-kubernetes-ingress/pull/132
- Adding `SslRedirectConfigurationName` to `frontendListenerAzureConfig`
- Adding `generateSSLRedirectConfigurationName()`
Tests will start running on TravisCI (via cmake) once https://github.com/Azure/application-gateway-kubernetes-ingress/pull/141 is comitted.
=> internaltypes: Adding generateSSLRedirectConfigurationName func; Extend frontendListenerAzureConfig struct

pkg/controller/controller.go, pkg/controller/eventqueue.go
In this PR:
- Removing some usages of the empty interface for the specific type used. (To quote @robpike: "interface{} says nothing.")
- Removing the `bool` return vaule from `processEvent()` since it is not used
- Small tweak to the `ApplicationGateway deployment` log statement - subjectively clarifying the semantics of the log line.
=> Stricter types for event passing; Simplify processEvent

pkg/utils/unorderedset.go, pkg/utils/unorderedset_test.go
Adding `ToSlice()` to our implementation of Sets in Go.
Would like to get this library closer to https://github.com/deckarep/golang-set and eventually replace it with it.
=> unorderedset: Adding ToSlice()

pkg/appgw/test_fixtures.go
Pulling a small piece of a [larger PR](https://github.com/Azure/application-gateway-kubernetes-ingress/pull/132) here.
With this change we createa more comprehensive `appGwConfigBuilder` struct.
=> tests: Augmenting test fixtures with needed structs

pkg/controller/controller.go, pkg/controller/eventqueue.go
@asridharan Following up on [your comment](https://github.com/Azure/application-gateway-kubernetes-ingress/pull/149#discussion_r281185114) on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/149 and my promise to introduce this Interface.
Here it is - a bit verbose, but otherwise unambigous interface: `QueuedEventEventProcessor`
=> controller: Introducing EventProcessor interface - provides an event actor

pkg/utils/unorderedset_test.go
We saw this fail once [here](https://travis-ci.org/Azure/application-gateway-kubernetes-ingress/builds/528959776?utm_source=github_status&utm_medium=notification):
```
--- FAIL: TestToSlice (0.00s)
unorderedset_test.go:25: 
Expected: [one two]
Actually: [two one]
```
=> unordered-set: Fix flaky test

pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/internaltypes.go, pkg/appgw/requestroutingrules.go, pkg/controller/controller.go
1) For loop ingresses/rules/paths with index to avoid making copies as we are using their addresses to create struct that are used as map keys.
2) Add IngressRule and IngressPath to backendIdentifier struct. Idea is to hold information relating a request routing rule (path to backend) in one struct and flatten ingress list.
=> for loop using idx and rule & path in backendIdentifier

pkg/appgw/backendhttpsettings.go
A new log statement to help w/ the discussion around handling long HTTP settings names: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/128
=> internaltypes: Log the name of the new HTTP setting

pkg/appgw/internaltypes_test.go
We are going to make certain changes to these key generation functions.
Let's wrap them with tests to ensure whatever changes we make produce sensible results.
Future changes to these functions:
- limit output to 80 characters
- change prefix
=> internaltypes: Adding basic tests for key generation

pkg/appgw/certificates.go, pkg/appgw/certificates_test.go, pkg/appgw/frontend_listeners.go, pkg/appgw/http_listeners.go, pkg/appgw/ingress_rules.go, pkg/appgw/ingress_rules_test.go
This PR is a chunk of the larger refactor from PR https://github.com/Azure/application-gateway-kubernetes-ingress/pull/156
In this PR:
- we create a new file - `frontend_listeners.go` with function `getListenerConfigs`, which constructs listener config for App Gwy from the given list of Ingresses -- this file will be fleshed out in following commits including unit tests for `frontend_listeners`
- we create new file `ingress_rules.go`, which introduces `processIngressRules`.  This function constructs the sets of front end listeners, ports and the corresponding Azure Config for these listeners.
- with these changes we also all uses of the old version of `getCertificate` (and delete the code) to the new `getCertificate`, which was introduced with …
=> Carving out the functions processing ingress rules into a separate file

pkg/appgw/internaltypes.go, pkg/appgw/internaltypes_test.go
Applying the new `governor` function to all property name generators.
Also ensuring with a unit test that the output of these functions is unique.
=> All generated prop names must be <= 80 characters and be unique

pkg/appgw/appgw_test.go, pkg/appgw/certificates_test.go, pkg/appgw/health_probes_test.go, pkg/appgw/ingress_rules_test.go, pkg/appgw/test_fixtures.go
Following up on a comment (https://github.com/Azure/application-gateway-kubernetes-ingress/pull/180#discussion_r284369840) - renaming all test fixture creators so they start with `new*` in lieu of `make*`
At some point we should move these functions in their own namespace and even further simplify the names.
No functional code changes in this PR.
=> tests: Rename functions creating test fixtures so they start with new in lieu of make

cmd/appgw-ingress/main.go
Let's call `glog.Flush()` to ensure we don't miss log lines.
Documentation: https://godoc.org/github.com/golang/glog
=> glog: Flush before exiting main()

cmd/appgw-ingress/env_variables.go, cmd/appgw-ingress/main.go
This merely rearranges sections of main.go and cleans up unnecessary constructs;
- often times we use `glog.Fatalf("Error: %v", err.Error())`, which is unnecessary;  `glog.Fatal("Error:", err)` achieves the same
- renamed `newEnvVariables` --> `getEnvVars` and moved validation there.
- moved the waiting-on-Azure-auth block into its own func `waitForAzureAuth`
- removed a few `for true {...}` -- `for {...}` does the same
- replaced the last `for true { time.Sleep(1 * time.Minute) }` with an empty `select` -- the empty `select{}` will block indefinitely while yielding CPU, unlike `for` loops
- removed the aliasing of the `flag` and `pflag`
=> Cleanup main.go & env_variables.go

pkg/appgw/appgw_test.go
In https://github.com/Azure/application-gateway-kubernetes-ingress/pull/156 we are getting a test, which explicitly requires a PublicIP address.
This PR adds one to the tests.
=> appgw_test: Add a PublicIPAddress to tests

pkg/appgw/frontend_listeners.go
This is covered by tests that are coming w/ https://github.com/Azure/application-gateway-kubernetes-ingress/pull/156/files
=> frontend_listeners: Fixing a bug in constructing Fatal error message

pkg/appgw/certificates_test.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/health_probes_test.go, pkg/appgw/ingress_rules_test.go, pkg/appgw/internaltypes_test.go
We don't need all these Ginkgo runners.
The following is sufficient for the entire package:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/appgw/appgw_suite_test.go#L10-L13
=> We need only one Ginkgo test launcher

pkg/appgw/frontend_ports.go, pkg/appgw/frontend_ports_test.go
Two of the files from PR https://github.com/Azure/application-gateway-kubernetes-ingress/pull/156
This should make reviewing https://github.com/Azure/application-gateway-kubernetes-ingress/pull/156 easier.
This PR introduces a function called `getFrontendPorts()` which when given a list of K8s Ingresses, returns a list of `ApplicationGatewayFrontendPort` to be created / applied.
=> appgw: Carving out frontend ports related functions in separate files

pkg/appgw/appgw_test.go, pkg/appgw/backendhttpsettings.go
This change uses a map in lieu of a slice to ensure that we do not generate `BackendHTTPSettings` with the duplicate names.
When this happens ARM responds w/ the following error: 
```bash
W0528 18:16:17.978860   13648 controller.go:118] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"DuplicateResourceName","message":"Resource /subscriptions//resourceGroups//providers/Microsoft.Network/applicationGateways/ has two child resources with the same name (bp-default-websocket-service-80-8888-websocket-ingress)."}]]
```
One can get into such state w/ the following Ingress definition. (The use of duplicate …
=> BackendHTTPSettings: Ensure unique names

pkg/appgw/requestroutingrules.go
@marceldiass pointed out that in certain Ingress configs we run into an error and cannot apply App Gwy config to ARM.
Looking at the YAML that could result in this error - it is a valid scenario.
Here is the ARM error as it is surfaced in the Ingress pod's logs:
```sh
W0528 18:27:53.847420   14709 controller.go:118] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayPathRulePathShouldHaveNonEmptyMatchValue" Message="Path / should have a nonempty match value followed by '/'  in PathRule /subscriptions/d664a618-e0fd-447e-a2cf-e0ca50ef6456/resourceGroups/derayche-rg-X/providers/Microsoft.Network/applicationGateways/applicationgateway85a7/urlPathMaps/url-x.mis.li-80/p …
```
=> rules: Handle slash path

pkg/appgw/appgw_test.go
We don't have guarantees on the order of the elements here in this test.
Also, unless I misunderstand how App Gateway v2 works, the order of Backend HTTP settings does not matter.
This test has been flaking once in a while; to stop this - we will check membership instead of position and equality.
=> appgw_test: No guarantees on the order of Backend HTTP Settings

pkg/controller/controller.go
If we run into an error while applying App Gwy config, reset the cache so it could be re-constructed and re-applied next time around.
=> controller: Wipe cache if updating ARM fails

pkg/controller/controller.go, pkg/controller/helpers.go
On failure to apply config - let's dump the JSON.
The idea here is to provide a mechanism by which we can wipe sensitive data and then dump the JSON.
This PR proposes we delete `"sslCertificates"`, which I believe captures all keys that have sensitive information.
Logging at V5 should provide some additional protection from pumping too much noise into logs.
=> controller: On failure to apply config - log (sanitized) config

pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/utils/unorderedset.go
This PR removes the last usages of `ForEach` and marks the tool as deprecated.
With another PR we could remove the majority of UnorderedSet as it is no longer used (with some exceptions, still used in threadsafemultipmap)
=> Remove reliance on UnorderedSet

go.mod, go.sum, pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go, pkg/appgw/appgw_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/health_probes.go, pkg/appgw/ingress_rules.go, pkg/appgw/requestroutingrules.go, pkg/errors/errors.go, pkg/errors/errors_test.go, pkg/k8scontext/context.go, vendor/github.com/pkg/errors/.gitignore, vendor/github.com/pkg/errors/.travis.yml, vendor/github.com/pkg/errors/LICENSE, vendor/github.com/pkg/errors/README.md, vendor/github.com/pkg/errors/appveyor.yml, vendor/github.com/pkg/errors/errors.go, vendor/github.com/pkg/errors/stack.go, vendor/modules.txt
This PR takes out the parsing for string/bool/int32 to separate functions so that annotations just have to provide key and get the value. It will also returns errors like missing value/invalid content which can be used for validation later.
Also, carved out the backendhttpsettings obj creation.
=> Carve out annotation parsing and add errors package, carved out backend https settings

pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/ingress_rules.go, pkg/appgw/requestroutingrules.go
This PR adds annotations to modify http settings related to the backend connections.
| Annotation | Values | Default | BackendHttpSettings property |
| -- | -- | -- | -- |
| appgw.ingress.kubernetes.io/connection-draining | `bool` | `false` | ConnectionDraining.Enabled |
| appgw.ingress.kubernetes.io/connection-draining-timeout | `int32` | `30` | ConnectionDraining.DrainTimeoutInSec |
| appgw.ingress.kubernetes.io/cookie-based-affinity | `bool` | `false` | CookieBasedAffinity |
| appgw.ingress.kubernetes.io/request-timeout | `int32` | `30` | RequestTimeout |
Will add tests/documentation in following PRs.
=> annotations: adding annotations for backendhttpsettings

pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go
Using the following ingress:
```yaml
kind: Ingress
metadata:
name: websocket-ingress
annotations:
kubernetes.io/ingress.class: azure/application-gateway
appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
tls:
- hosts:
- ws.mis.li
secretName: testsecret-tls
rules:
- http:
paths:
- path: /
backend:
serviceName: websocket-service
servicePort: 80
```
ran into this error:
```sh
W0531 14:57:33.448468    2809 controller.go:133] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceReference" Message="Resource /subscriptions/.../resourceGroups/derayche-rg-X/providers/Microsoft.Network/applicationGateways/.../redirectConfigurations/sslr-default …
```
=> Fixing a bug with SSL redirects

pkg/controller/helpers.go, pkg/controller/helpers_test.go
`isMap` and `isSlice` could be passed an empty interface and need to deal with these cases
=> Ensure isMap and isSlice return false when checking nil

pkg/appgw/requestroutingrules_test.go, pkg/controller/controller.go, pkg/controller/helpers.go, pkg/controller/helpers_test.go
There are a few issues that I'd like to fix with the config cache:
1. no need to pre-allocate a byte array for that - we can start with none memory allocated
2. cleaning the cache should be as simple as setting it to a nil pointer
3. most importantly - I'd like to separate comparing config w/ cache and updating the cache -- these should have never been put together
=> Update cache separately from comparing cache with current config

pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendaddresspools_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/health_probes.go, pkg/appgw/health_probes_test.go, pkg/appgw/http_listeners.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/controller/controller.go
In all these cases below in is unnecessary to return `ConfigBuilder` since the function returning it already mutated the receiver and the changes are available to its peers.
The goal of this change is to:
- simplify functions' signatures
- remove the illusion that each function returning `ConfigBuilder` is without side-effects returning a copy of the struct.
=> Simplify return types

pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder_debug.go, pkg/appgw/frontend_listeners.go, pkg/appgw/health_probes.go, pkg/appgw/ingress_rules_test.go, pkg/k8scontext/context.go, pkg/utils/threadsafemultimap.go
There are multiple ways to make a slice, but they are not all equal.
Overall the performance loss is negligent given N in our case.
And yet - let's practice efficient and idiomatic Go.  (This mainly a reminder for myself as I'm fixing some of the unnecessary `make`s that I added)
Here is an interesting read on the topic: https://blog.golang.org/slices
=> Remove unnecessary memory allocations when making slices

docs/install-existing.md
In December 2018 when we used an older version of the underlying SDK we had to ensure we don't accidentally disable autoscale. So this blurb was added to the documentation.
As we discovered in https://github.com/Azure/application-gateway-kubernetes-ingress/issues/245 - this is no longer the case.
AGIC can work with Auto-scale enabled App Gateways as well.
=> Updating documentation to remove the constraint on Autoscale-disabled App Gateway; Fixes #245

cmd/appgw-ingress/main.go, pkg/controller/controller.go
This allows us to run `./bin/appgw-ingress --verbosity=5` and see the JSON that was posted to ARM
The use of both `flags` and `github.com/spf13/pflag` seems sub-optimal, but we'll leave that for another day.
=> main: Adding verbosity CLI flag; Sanitize and log the JSON config that was applied to App Gateway

pkg/appgw/requestroutingrules.go
Fixing a bug, which leaves `urlPathMapFiltered` unsorted
=> Sort urlPathmapFiltered

pkg/k8scontext/k8scontext_test.go, pkg/tests/fixtures.go
Moving and renaming 2 factories into the `tests` namespace
=> Move test fixture factories out of k8scontext and into tests package

pkg/appgw/health_probes.go
It turns out `[health-probes] ` prefix for these log statements is redundant:
As shown in the example below - we already know the file-name from which this log statement originates, which carries enough context:
`I0607 09:53:23.413308   25067 health_probes.go:28] [health-probes] Adding default probe:defaultprobe`
=> health_probes: Removing log statement prefix

pkg/appgw/requestroutingrules.go
This PR simplifies the generation of request routing rules by removing the order in which we append request routing rules:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/6771e9981736e21043a1bded4b2c00758f526f3c/pkg/appgw/requestroutingrules.go#L235-L240
=> Refactor requestroutingrules.go

pkg/appgw/ingress_rules.go, pkg/appgw/ingress_rules_test.go, pkg/appgw/redirects_test.go
Adding comprehensive tests:
- with TLS & with SSL Redirect Annotation
- without TLS & with Annotation
- with TLS & without Annotation
Fixes a bug where even without annotation we create a redirect.
This has not caused any issues since the unnecessary redirects have not been linked to routing rules.
=> Add more SSL Redirects tests and fix a bug

pkg/appgw/appgw_test.go, pkg/controller/controller.go, pkg/controller/eventqueue.go, pkg/events/events.go, pkg/k8scontext/handlers.go
This PR is a small chunk from https://github.com/Azure/application-gateway-kubernetes-ingress/pull/267
The move here is necessary to avoid a cyclical dependency && allow for reusability of the Event struct.
=> Move pkg/k8scontext/event.go to pkg/events/events.go

cmd/appgw-ingress/main.go, pkg/appgw/appgw_test.go, pkg/appgw/configbuilder.go, pkg/appgw/validators.go, pkg/appgw/validators_test.go, pkg/controller/controller.go
This PR divides the validate into three parts:
1) `FatalValidateOnExistingConfig`: These are validations which cause either the controller to crash or retry the event until the Application Gateway config is corrected or controller is redeployed with a new helm-config.
2) `PreBuildValidate`: These are validation error that suggest misconfiguration on k8s side like missing service, etc. But they don't prevent us from generating a config.
3) `PostBuildValidate`: These are errors which suggest that our generated application gateway config is invalid. These are fatal and will caught by `ARM`.
=> chore: Split Validation into FatalValidateOnExistingConfig, PreBuildValidate, PostBuildValidate

cmd/appgw-ingress/main.go, helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/values.yaml, pkg/appgw/appgw_test.go, pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/http_listeners.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/appgw/test_fixtures.go, pkg/appgw/validators.go, pkg/appgw/validators_test.go, pkg/controller/controller.go, pkg/tests/fixtures.go
This PR adds support to allow Ingress Controller to use private IP with the Application Gateway.
To enable using Private IP, modify the `helm` config by adding
```yaml
appgw:
subscriptionId: <subscriptionId>
resourceGroup: <resourceGroupName>
name: <applicationGatewayName>
usePrivateIP: true
armAuth:
type: aadPodIdentity
identityResourceID: <identityResourceId>
identityClientID:  <identityClientId>
kubernetes:
watchNamespace: <namespace>
rbac:
enabled: false
aksClusterConfiguration:
apiServerAddress: <aks-api-server-address>
```
This will make the ingress controller look for private ip when assigning the ip configuration for the listener.
Another solution to this could have been:
```yaml
appgw.ingress.kubernetes.io/use-private-ip: true
```
We are not implementing this one since …
=> feat: use Private IP with routing rules

pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendaddresspools_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/health_probes.go, pkg/appgw/health_probes_test.go, pkg/appgw/http_listeners.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/appgw/types.go, pkg/controller/controller.go, pkg/k8scontext/types.go
This PR proposes we use `appgw.ConfigBuilderContext {}` in lieu of a list of args for each top level Controller function.  Instead of passing around `ingressList`, `serviceList` etc - let's pass around a pointer to a struct that has these.
The motivation for this is - needing to pass around the new `AzureIngressManagedTarget` and `AzureIngressProhibitedTarget`.  It seems appropriate to pave the road for the next person who'd need to pass around a new struct - they would only have to add it to `ConfigBuilderContext `
```go
type ConfigBuilderContext struct {
IngressList       []*v1beta1.Ingress
ServiceList       []*v1.Service
ManagedTargets    []*mtv1.AzureIngressManagedTarget
ProhibitedTargets []*ptv1.AzureIngressProhibitedTarget
EnvVariables      environment.EnvVariables
}
```
At a high …
=> [RFC] Use k8scontext.KubernetesResources to pass common arguments around

cmd/appgw-ingress/main.go, docs/examples/helm-config.yaml, docs/install-existing.md, docs/install-new.md, helm/ingress-azure/templates/NOTES.txt, helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml, pkg/environment/environment.go, pkg/environment/fake.go
I realize that we have great logging (and improving), but no easy way to enable that on the actual AGIC pod.
This PR adds:
- `APPGW_VERBOSITY_LEVEL` environment variable to the Docker container
- `verbosityLevel` to the Helm templates
- read both - `APPGW_VERBOSITY_LEVEL` over `verbosityLevel` CLI flag
When AGIC starts - we see:
- `Using verbosity level 5 from environment variable APPGW_VERBOSITY_LEVEL`
or 
- `Using verbosity level 1 from CLI flag verbosity`
Having this environment variable would enable customers to easily bump verbosity to `5` so that they can see (sanitized) App Gateway config / JSON being applied to ARM. (w/ `kubectl logs ...`)
=> [RFC] Adding VERBOSITY_LEVEL env var; Add to helm template

helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/values.yaml
This PR fixes the configmap template.
Configmap can only take a list `string: string` in data field.
When verbosityLevel: 3 is passed from the values.yaml, helm deployment fails with error.
```bash
Error: UPGRADE FAILED: v1.ConfigMap.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: ReadString: expects " or n, but found 3, error found in #10 byte of ...|Y_LEVEL":3,"KUBERNET|..., bigger context ...|-xxx","APPGW_VERBOSITY_LEVEL":3,"KUBERNETES_WATCHNAMESPACE":"default","USE_PRIVAT|...
```
=> fix: error creating configmap and rbac default: false

cmd/appgw-ingress/main.go, pkg/appgw/appgw_test.go, pkg/controller/controller.go, pkg/environment/environment.go, pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go
This PR introduces 2 new environment variables, to serve as feature flags.
Behind these feature flags we hide the Brownfield work currently in progress, and will hide the Istio integration. The overall goal is to introduce a mechanism by which we can toggle portions of the software.
This could be further improved by separating the feature flags into their own struct and introducing better types (than simply comparing to some string) - this could come at a later stage.
=> Introducing feature flags controlling brownfield deployment and Istio integration

docs/troubleshooting.md
We should start fleshing out the troubleshooting section so that customers can have the resources needed to understand and correct issues as these arise.
=> Fleshing out some of the Troubleshooting documentation

helm/ingress-azure/templates/clusterrole.yaml
This PR modifies the cluster role to
1) allow create/patch on events
2) allow list/get/watch on `appgw.ingress.k8s.io`/`networking.istio.io` apiGroup CRDs.
```bash
Name:         odd-billygoat-ingress-azure
Labels:       app=ingress-azure
chart=ingress-azure-0.7.0-rc1
heritage=Tiller
release=odd-billygoat
Annotations:  <none>
PolicyRule:
Resources                    Non-Resource URLs  Resource Names  Verbs
---------                    -----------------  --------------  -----
events                       []                 []              [get list watch create patch]
configmaps                   []                 []              [get list watch]
endpoints                    []                 []              [get list watch]
namespaces                   []                 [] …
```
=> helm: modify clusterrole for events and appgw.ingress.k8s.io/networking.istio.io crds

cmd/appgw-ingress/main.go, docs/troubleshooting.md, pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/certificates.go, pkg/appgw/configbuilder.go, pkg/appgw/internaltypes.go, pkg/appgw/redirects.go, pkg/appgw/requestroutingrules.go, pkg/appgw/validators.go, pkg/controller/controller.go, pkg/controller/eventqueue.go, pkg/events/events.go, pkg/events/types.go
For customers with many namespaces, logging volume could get overwhelming.
Reusing the semantics from [kubectl](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging) verbosity logging - introducing 3 levels:
| Verbosity | Description |
|-----------|-------------|
|  1        | Default log level; shows startup details, warnings and errors |
|  3        | Extended information about events and changes; lists of created objects |
|  5        | Logs marshaled objects; shows sanitized JSON config applied to ARM |
Added section to the Troubleshooting doc on how to change verbosity setting.
With `verbosity==1`:
```
Version: 0.7.0-rc2; Commit: 05d27892; Date: 2019-06-25-12:48T-0700
ERROR: logging before flag.Parse: I0625 12:48:47.641806   20750 …
```
=> Refactor logging into 3 verbosity levels; Document

docs/tutorial.md
Let's Encrypt was moved from tutorials to How to section in Pullrequest #295
=> Remove let's encrypt anchor in Tutorials

cmd/appgw-ingress/main.go, pkg/appgw/appgw_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/certificates.go, pkg/appgw/configbuilder.go, pkg/appgw/frontend_ports.go, pkg/appgw/frontend_ports_test.go, pkg/appgw/health_probes.go, pkg/appgw/health_probes_test.go, pkg/appgw/identifier.go, pkg/appgw/ingress_rules.go, pkg/appgw/internaltypes.go, pkg/appgw/requestroutingrules.go, pkg/appgw/test_fixtures.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/helpers.go, pkg/controller/helpers_test.go
While working on the brownfield-deployment feature, I noticed that we are not benefiting much from the `network.` prefix in the SDK's structs. Instead these cause for long function signatures and subjectively verbose code.
The structs from the SDK are already with very high specificity - for instance `network.ApplicationGatewayProbe`.  Shortening this to `n.ApplicationGatewayProbe` does not reduce clarity.
In [quite a few files we are already](https://github.com/Azure/application-gateway-kubernetes-ingress/search?utf8=%E2%9C%93&q=n+%22github.com%2FAzure%2Fazure-sdk-for-go%2Fservices%2Fnetwork%2Fmgmt%2F2018-12-01%2Fnetwork%22&type=) employing this aliasing. The PR here completes the work across 100% of the imports.
=> Alias the Azure SDK network package

docs/how-tos/helm-upgrade.md
A few small tweaks to the upgrade documentation to bring it to consistency with the rest of our docs:
- removing custom shell prompt
- capitalize Helm
- split `&&` commands
- split into multiple lines where lines too long
=> Update Helm upgrade documentation

pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/health_probes.go, pkg/appgw/requestroutingrules.go
Reusing the `ConfigBuilderContext` to shorten the signatures of some functions.
This in preparation for the brownfield deployment...
=> Refactor function signatures to reuse ConfigBuilderContext

pkg/utils/utils.go, pkg/utils/utils_test.go
This tiny utility comes-in handy when one wants to get the last piece (the resource name) of a Resource Id.
For instance
when given `/subscriptions/yxxxyxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/draychev-rg-X/providers/Microsoft.Network/applicationGateways/applicationgatewayxxxx/redirectConfigurations/sslr-fl-app3.domain.com-443`
it will return `sslr-fl-app3.domain.com-443`
=> utils: Adding GetLastChunkOfSlashed - returns the last slice of a string split on slash

crds/AzureIngressManagedTarget.yaml, crds/AzureIngressProhibitedTarget.yaml, crds/examples/AzureIngressManagedTarget.yaml, crds/examples/AzureIngressProhibitedTarget.yaml, proposals/config_ownership_crd.md
Changing this documentation (not in Helm yet) to match the Go code:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/71b94ef2aaa5ffb47d26aa93f0221241436b775f/pkg/apis/azureingressmanagedtarget/v1/types.go#L25-L44
=> AzureIngress{Managed,Prohibited}Target: renaming host to hostname

pkg/controller/controller.go, pkg/controller/process.go, pkg/eventqueue/eventqueue.go, pkg/eventqueue/types.go
Idea is that controller should not know about eventqueue.
Controller's job is just to start k8sContext and EventQueue and facilitate communication between them. I am still getting clarity on how the code should look like.
For process, I have moved it to process.go, let me know if you have any better ideas.
=> controller: Moving eventqueue to it's own folder and new file for process function in Controller

pkg/controller/controller_suite_test.go, pkg/environment/environment_suite_test.go, pkg/tests/tests_suite_test.go
ginkgo tests requires each package to have a RunSpec function to be able run the tests.
If not found, it says, `no tests to run`
Here is an issue mentioning the same.
https://github.com/onsi/ginkgo/issues/344
=> tests: add test suite files

pkg/worker/fake.go, pkg/worker/types.go, pkg/worker/worker.go, pkg/worker/worker_suite_test.go, pkg/worker/worker_test.go
This PR is first part of replacing `eventqueue`.
It adds a simple worker process which listens on the `eventChannel` linked to `k8sContext`.
=> eventqueue: simple worker

pkg/controller/process.go, pkg/k8scontext/context.go, pkg/tests/fixtures/paths.go, pkg/tests/fixtures/pools.go
This PR continues the trend of cleaning up `process.go` and moves the logging of `AzureIngressManagedTargets` and `AzureIngressProhibitedTargets` into the appropriate Lister functions within `context.go`
These log statements are at verbose level and for debug purposes.
=> context: Log found Managed/Prohibited Targets within the Lister functions

pkg/k8scontext/context.go, pkg/sorter/ingress.go
This PR ensures the results of `k8scontext.ListHTTPIngresses()` (a list of Kubernetes Ingress resources) is sorted.
This increases cache hits, lowers the number of times we have to post new config to ARM.
=> ingress: Add sorter for deterministic ARM config

pkg/controller/helpers.go, pkg/controller/process.go, pkg/environment/environment.go, scripts/start.sh
This PR introduces the ability to log App Gateway config to a file. 
This is enabled with env variable `APPGW_ENABLE_SAVE_CONF="true"`
The Gateway config is sanitized:
- it will *not* include secrets
- the etags are deliberately kept for debugging
Motivation for this change:  it proves very helpful to see actual config logged, perhaps diff between different posts to see what has changed etc.
=> Log App Gateway config to file w/ feature flag APPGW_ENABLE_SAVE_CONF

helm/release.sh
Since, we are moving helm `index` and `gz` files to storage, they will not be pushed to github.
In future, when we run the `helm repo index` command, it will not take care of the `gz` present on the storage and will omit them in the new index file.
Solution is to pull the old index file and merge using `helm repo index --merge`
=> pipelines: merge with current index file in helm repo

pkg/appgw/certificates.go, pkg/appgw/frontend_ports.go, pkg/appgw/frontend_ports_test.go, pkg/appgw/http_listeners.go, pkg/appgw/redirects.go, pkg/appgw/redirects_test.go
This is a small chunk from https://github.com/Azure/application-gateway-kubernetes-ingress/pull/345
Moving this here so https://github.com/Azure/application-gateway-kubernetes-ingress/pull/345 can thin out a bit.
In this PR we reuse `ConfigBuilderContext` instead of passing the` Ingres`s list around (which is a subset of `ConfigBuilderContext` struct)
=> Reuse ConfigBuilderContext to simplify

pkg/appgw/types.go, pkg/brownfield/brownfield_suite_test.go, pkg/brownfield/brownfield_test.go, pkg/brownfield/ingress.go, pkg/brownfield/ingress_test.go, pkg/brownfield/targets.go, pkg/brownfield/targets_test.go, pkg/brownfield/types.go, pkg/controller/process.go
This PR introduces (a partial implementation of) brownfield deployment.
This is a the first part of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/345.
In this PR we trim the rules of the Ingress resource down to what AGIS is allowed to configure App Gwy for.
The strategy is described in [a proposal here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/proposals/config_ownership_crd.md).
=> Prune Ingress Rules based on  AzureIngress{Managed,Prohibited}Target CRDs

pkg/brownfield/ingress.go, pkg/brownfield/ingress_test.go, pkg/brownfield/targets.go, pkg/brownfield/targets_test.go
The `Target` struct is unnecessarily complex. Let's simplify it.
This PR is a small piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/345
=> Simplify Target{} Struct

pkg/appgw/internaltypes.go
Removing an unnecessary variable.
=> internaltypes: Simplify defaultBackendAddressPool

pkg/appgw/backendaddresspools.go, pkg/appgw/configbuilder.go, pkg/appgw/internaltypes.go, pkg/brownfield/ingress.go, pkg/brownfield/ingress_test.go, pkg/brownfield/pools.go, pkg/brownfield/pools_test.go, pkg/brownfield/targets_test.go, pkg/brownfield/types.go, pkg/tests/fixtures/http_settings.go, pkg/tests/fixtures/ips.go, pkg/tests/fixtures/listeners.go, pkg/tests/fixtures/paths.go, pkg/tests/fixtures/pools.go, pkg/tests/fixtures/ports.go, pkg/tests/fixtures/routing_rules.go, pkg/tests/fixtures/targets.go
This PR introduces (a partial implementation of) brownfield deployment.
The strategy is described in [a proposal here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/proposals/config_ownership_crd.md).
The overall goal is to define certain targets (think `domain/url`) via the `AzureIngressProhibitedTarget` CRD that are blacklisted, which AGIC will not mutate or overwrite. These will be retained as they exist in App Gateway.
This would allow an administrator to *manually* configure some settings on Application Gateway, while allowing the ingress controller to set others.
- this PR implements target blacklist for backend pools only
- using feature flag to guard these changes (until they are fully fleshed out and tested): …
=> pools: Apply blacklist based on AzureIngressProhibitedTarget CRDs

pkg/controller/should_process.go, pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go, pkg/tests/fixtures.go, pkg/worker/fake.go, pkg/worker/types.go, pkg/worker/worker.go
This PR aims to the reduce the churn in the events. Events relate to Pod or Endpoints updates which can be occurring at 1 per sec. This hurts when users are in process of manually updating the gateway and then the controller overwrites the changes.
This PR will be followed by using `Etag` when calling `PUT` on Gateway.
=> events: skip pod and endpoints events when unrelated to ingress

pkg/brownfield/types.go
The `ExistingResources` struct will become the core class around which brownfield deployment will revolve as illustrated in the following PR, containing the entire feature: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
ExistingResources is used in brownfield deployments and holds a copy of the existing App Gateway config, based on which AGIC will determine what should be retained and what config should be discarded or overwritten.
=> brownfield: Adding new ExistingResources struct

pkg/appgw/backendhttpsettings.go, pkg/appgw/health_probes.go
Renaming the variables to indicate that these are created by AGIC.
This is a tiny PR to remove some of the load from https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
=> brownfield: Rename variables to clarify the origin of the config

pkg/brownfield/listeners.go, pkg/brownfield/pathmaps.go, pkg/brownfield/pathmaps_test.go, pkg/brownfield/routing_rules.go, pkg/brownfield/routing_rules_test.go, pkg/brownfield/types.go, pkg/tests/fixtures/app_gateway.go
This PR is a small piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369, but it is the heart of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369.
The primary goal of this PR is to add:
- `GetBlacklistedPathMaps()`
- `GetBlacklistedRoutingRules()`
Based on these two lists we can determine whether any of the other App Gateway resources are blacklisted or not (since everything else is in one way or another linked to a `RoutingRule`)
=> brownfield: Routing Rules

docs/how-tos/helm-upgrade.md, docs/setup/install-existing.md, docs/setup/install-new.md, helm/index.md, helm/index.yaml
This updates the all reference to the github helm repo to Azure helm repo.
After adding mkdocs, helm links are not working as expected.
=> helm: updating helm repo path to Azure blobs

pkg/appgw/backendaddresspools.go, pkg/brownfield/pools.go, pkg/brownfield/pools_test.go, pkg/brownfield/types.go
This PR depends on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 and is a small piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
We leverage the `GetBlacklistedRoutingRules()` introduced in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 to determine what `HTTP Settings` are also blacklisted.
=> brownfield: Backend Address Pools

pkg/appgw/backendhttpsettings.go, pkg/brownfield/http_settings.go, pkg/brownfield/http_settings_test.go
This PR depends on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 and is a small piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
We leverage the `GetBlacklistedRoutingRules()` introduced in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 to determine what `HTTP Settings` are also blacklisted.
=> brownfield: HTTP Settings

pkg/appgw/backendaddresspools.go, pkg/appgw/configbuilder.go
Removing `ConfigBuilder` helper functions in lieu of using ones provided by `ExistingResources` (and introduced with https://github.com/Azure/application-gateway-kubernetes-ingress/pull/376)
This depends on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/385
=> configbuilder: Remove unnecessary methods

pkg/appgw/frontend_listeners.go, pkg/brownfield/listeners.go, pkg/brownfield/listeners_test.go
This PR depends on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 and is a small piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
We leverage the `GetBlacklistedRoutingRules()` introduced in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374  to determine what `HTTP Listeners` are also blacklisted.
=> brownfield: HTTP Listeners

pkg/appgw/certificates.go, pkg/brownfield/certificates.go, pkg/brownfield/certificates_test.go
This PR depends on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 and https://github.com/Azure/application-gateway-kubernetes-ingress/pull/381, and is a small piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
We leverage the `GetBlacklistedListeners()` introduced in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/381 to determine what `SSL Sertificates` are also blacklisted.
=> brownfield: Certificates

pkg/appgw/frontend_ports.go, pkg/brownfield/ports.go, pkg/brownfield/ports_test.go
This PR depends on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 and https://github.com/Azure/application-gateway-kubernetes-ingress/pull/381, and is a small piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
We leverage the `GetBlacklistedListeners()` introduced in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/381 to determine what `Frontend Ports` are also blacklisted.
=> brownfield: Frontend Ports

pkg/appgw/health_probes.go, pkg/brownfield/health_probes.go, pkg/brownfield/health_probes_test.go
This PR depends on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 & https://github.com/Azure/application-gateway-kubernetes-ingress/pull/380 and is a small piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
We leverage the `GetBlacklistedHTTPSettings()` introduced in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374 to determine what `Health Probes` are also blacklisted.
=> brownfield: Health Probes

pkg/appgw/types.go, pkg/controller/process.go
This PR creates `EnableIstioIntegration` as a first-class feature flag within the `ConfigBuilderContext` struct.
We also reorganize the population of the `ProhibitedTargets`, `IstioGateways`, and `IstioVirtualServices` so that these happen only of the dedicated feature flag is on.
=> Introducing EnableIstioIntegration feature flag within the ConfigBuilderContext struct

pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/internaltypes.go
This PR creates a function to generate the service backend pair map (to be used in creating the BackendAddressPools), and sets up the general structure for creating the HTTP Settings map.
=> Istio Backend and HTTP Settings Map

pkg/appgw/backendaddresspools.go
Reconfigure backend address pools using istio virtual service information. This mostly just builds on the last PR by taking the destination IDs and creating a backend address pool for each one.
=> Istio Backend Address Pools

pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_ports.go
Creating App Gateway listeners from Istio `Gateways` and `VirtualServices` ([ref](https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/))
=> istio: Setup Listeners + Frontend Ports from Gateways and VirtualServices

pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendaddresspools_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/certificates.go, pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/frontend_ports.go, pkg/appgw/frontend_ports_test.go, pkg/appgw/health_probes.go, pkg/appgw/health_probes_test.go, pkg/appgw/identifier.go, pkg/appgw/internaltypes.go, pkg/appgw/redirects.go, pkg/appgw/redirects_test.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go
This PR sets the sub-resource's resourceId so that it can be used to perform lookups.
This is sub-part to brownfield work.
#396
=> chore: set resourceIds in subresources

pkg/controller/controller.go, pkg/k8scontext/context.go
This PR:
1. starts worker after context so that context can finish sync up.
1. Add event handler for prohibited CRD.
=> start worker after context, eventhandler for prohibited crd

pkg/appgw/appgw_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/health_probes.go
This PR fixes port resolution.
In case when we get a targetport as string, we do a lookup on endpoints object to get the port using the target port name.
But endpoints object contains port with `Name` taken from service Port. So the lookup should happen using service's port name.
Fixes #372
=> fix: port resolution when targetPort is string

cmd/appgw-ingress/main.go
This PR adds:
1. moves the getAzAuth into the retry loop. When a permission is changed, a new token is needed to move over 403
1. reasons for 403
=> fix: retry and 403 reasons

pkg/appgw/redirects.go, pkg/appgw/requestroutingrules.go
This PR increases the log level from 3 to 5 for routing rules and redirect configurations.
These are informational messages and we emit lots of them.
Level 3 should be reserved for warnings and errors.
=> redirects: Bump log level from 3 to 5 to reduce noise

pkg/appgw/types.go, pkg/controller/process.go, pkg/environment/environment.go
I have been using the code in this PR to help me find PUT errors (and stop so I can troubleshoot these).
This introduces an env variable `APPGW_ENABLE_PANIC_ON_PUT_ERROR`, which when set to `"true"`, causes AGIC to panic on PUT error.
This is to be used in dev environment only. (Although it may be beneficial to kill the container if a PUT error occurs in prod as well)
=> Panic on ARM PUT error

crds/AzureIngressProhibitedTarget.yaml
Tweaking the regex of the `AzureIngressProhibitedTarget` CRD to allow for `/*` wild card URL.
The change:
`'^\/.*\/\*$'` --> `'^\/(?:.+\/)?\*$'`
1. adding `(?:    )` creates a non-capturing group
2. adding `?` after the group - makes it optional
=> Correct AzureIngressProhibitedTarget CRD URL pattern to allow for '/*'

cmd/appgw-ingress/main.go
Clarifying the error below to be more informative.
New error looks like this:
```bash
ERROR: logging before flag.Parse: I0724 11:58:49.047950    5802 main.go:275] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0724 11:58:49.048232    5802 main.go:225] Creating authorizer from file referenced by AZURE_AUTH_LOCATION environment variable: /home/xxx/.azure/azureAuth.json
E0724 11:58:49.701161    5802 main.go:194] Failed fetching config for App Gateway instance applicationgatewayxxx. Will retry in 10s. ARM Error: network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'xxx' could not be found."
```
=> logging: Adding clarity to an ARM error 

go.mod, go.sum, pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go, pkg/appgw/internaltypes.go, pkg/appgw/istio_config.go, pkg/appgw/istio_listeners.go, pkg/appgw/istio_pools.go, pkg/appgw/istio_settings.go, pkg/appgw/istio_types.go, pkg/k8scontext/context.go, pkg/k8scontext/istio_context.go
This PR is a no-op. Simply moving Istio related functions into separate files, but still within the same packages.
This separates concerns and lowers cognitive load when working within these files -- also lowers the chance of stepping on each others toes / merge conflicts etc.
=> Move istio specific functions in seprate files

pkg/appgw/frontend_listeners.go, pkg/appgw/requestroutingrules.go
I accidentally stumbled on these 2 lines of code.  I thought we removed most of the side-effects - it seems that we missed these.
Removing the dependency on the order of operations would remove the risk of running into incorrect config generation and would allow us to enable concurrency.
On the other hand - there is obviously redundant work that is going to be done here.
At a later stage we should introduce memoization (should performance become an issue)
=> Ensure pure functions / idempotency

pkg/appgw/redirects.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/tests/fixtures/ingress.go
In certain complex scenarios we run into an edge case where the list of `"redirectConfigurations": []` does not have the redirect we are still attaching it to a URLPathMap's rule (adding it to the lits `urlPathMaps..pathRules..redirectConfiguration=[...]`)
Regardless of the reason for which the SSL Redirect was *not* created - we should *not* construct an invalid JSON.
This PR removes the invalid reference end logs an error:
```
E0723 18:14:36.913659   18089 requestroutingrules.go:282] Will not attach redirect to rule; SSL Redirect does not exist: /subscriptions/xxx/resourceGroups/aa-rg-Z/providers/Microsoft.Network/applicationGateways/applicationgatewayaaaa/redirectConfigurations/sslr-fl-ws.mis.li-443
```
Example:
```
F0723 17:56:22.846431   17592 process.go:127] Failed applying App Gwy …
```
=> Skip attachment of non-existent redirects

pkg/brownfield/ingress.go, pkg/brownfield/routing_rules.go, pkg/brownfield/targets.go, pkg/brownfield/targets_test.go
In this PR:
- Introducing new type `TargetPath`, which is a string -- a URL Path - `/x/*` for example
- adding a `contains` function to inform whether path N is contained within path M
Example:
```yaml
apiVersion: appgw.ingress.k8s.io/v1
kind: AzureIngressProhibitedTarget
metadata:
name: blacklist-all-targets
spec:
paths:
- /*
```
should blacklist `/abc` and all other paths.
(This here is required for https://github.com/Azure/application-gateway-kubernetes-ingress/pull/412/files#diff-09ce61e60cf8eae7f9ff52a875eafea7R40)
=> brownfield: TargetPath.contains(TargetPath)

cmd/appgw-ingress/errors.go, cmd/appgw-ingress/main.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/errors.go, pkg/appgw/validators.go, pkg/brownfield/errors.go, pkg/brownfield/routing_rules.go, pkg/controller/errors.go, pkg/controller/process.go, pkg/k8scontext/context.go, pkg/k8scontext/errors.go
The goal of this PR is to establish a pattern where we instantiate types of errors once, and then reuse these globals.
This affords us easier error checking / error comparison.
Example (https://play.golang.org/p/S0Y2_0qBsbi):
```golang
package main
import (
"errors"
"fmt"
)
var ErrBlah = errors.New("blah")
func m() error { return ErrBlah }
func n() error { return ErrBlah }
func main() {
fmt.Println("Hello, playground")
a := errors.New("blah")
b := errors.New("blah")
fmt.Println(a == b)     // false
fmt.Println(m() == n()) // true
}
```
=> errors: Make errors.New() singletons - into errors.go

pkg/appgw/errors.go, pkg/appgw/validators.go, pkg/appgw/validators_test.go
This PR fixes the issue shown in the log below.
We should return a meaningful error. The root cause for missing config are permission issues; the nil pointer dereference issue is actually ok, but adds noise and distracts from quickly arriving at the actual issue at hand.
```bash
E0724 22:06:00.508471       1 main.go:179] Error getting Application Gatewayapplicationgatewayd0f0azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationGateways/xxx?api-version=2018-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: no AzureAssignedIdentity found for pod:default/ingress-azure-xx-xx
I0724 22:06:00.508514 …
```
=> validators: Check for nil App Gateway config

helm/ingress-azure/templates/deployment.yaml, helm/ingress-azure/templates/secrets.yaml, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml
This PR corrects and simplifies the option to provide Service Principal auth to AGIC.
Changes:
- hard coded the Kubernetes secret name to: `networking-appgw-k8s-azure-service-principal` (I don't see a reason to allow for this to be tweaked, except of course in cases where the name would collide with some other existing secret; given the specificity of the string - I can't imagine a situation where this would occur)
- hard coded the filename where the the secret would me mounted to: `armAuth.json`
- the service principal JSON blob will be provided via new key -- `secretJSON`
- added instructions on how to generate the `secretJSON`
Documentation still needs to be updated on how to use this method of authenticating against ARM. This will come in another PR.
=> helm: Hard-code secretName to networking-appgw-k8s-azure-service-principal

pkg/appgw/redirects.go, pkg/brownfield/redirects.go, pkg/brownfield/targets.go, pkg/brownfield/types.go, pkg/controller/helpers.go, pkg/controller/process.go
Applying all the same patterns as we have done with the other App Gateway configuration resources - we now apply `AzureIngressProhibitedTarget` (blacklist) CRD to the `RedirectConfigurations`.
Additionally - adding helper to dump the config we obtained from App Gateway (at `glog.V(5)`)
=> brownfield: Redirect Configurations

pkg/appgw/configbuilder.go, pkg/brownfield/listeners.go, pkg/brownfield/listeners_test.go, pkg/brownfield/targets_test.go, pkg/brownfield/types.go, pkg/tests/fixtures.go, pkg/tests/fixtures/app_gateway.go, pkg/tests/fixtures/listeners.go
Looking at Routing Rules to determine whether a listener is prohibited is not sufficient.
When a customer is creating a now Listener, which is not yet connected to routing rules, AGIC will  delete it.
This PR proposes we look at hostnames to determine whether a listener is prohibited.
We retain the current functionality of also looking at routing rules -- this is useful in the cases where a listener does not have a hostname, but is linked to a prohibited URL.
=> brownfield: Determine whether a listener is prohibited based on hosts first

docs/examples/sample-helm-config.yaml, helm/ingress-azure/templates/NOTES.txt, helm/ingress-azure/templates/azureingressprohibitedtarget.yaml, helm/ingress-azure/templates/configmap.yaml
This PR:
- makes it possible to enable brownfield deployment via `helm --set brownfield.enabled=false`
- adds `AzureIngressProhibitedTarget` CRD to helm chart
- adds `blacklist-all-targets` AzureIngressProhibitedTarget by default, which as the name implies - by default blacklists all traffic targets
=> Adding AzureIngressProhibitedTarget to Helm

pkg/appgw/istio_pools.go
```go
package main
import (
"fmt"
"strconv"
)
func main() {
port := 8000
fmt.Println("Hello, playground", port, string(port), " vs ", strconv.Itoa(port))
}
```
`Hello, playground 8000 ὀ  vs  8000`
=> fixed string type conversion issue

pkg/controller/process.go
In a Kubernetes setup where we have Istio, but no Ingress definition, this conditional would terminate the processing of the given event.  To get istio ingress working - we need this to continue.
=> istio: Do look for istio primitives even when no Ingresses are defined

pkg/appgw/istio_settings.go
The `defaultBackend` will be added by `getBackendsAndSettingsMap` [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/f1464dbd2a1f2d6ba0917f54d9ac73395b5fccca/pkg/appgw/backendhttpsettings.go#L198)
`getIstioDestinationsAndSettingsMap` then does not need to add a default backend.
We can safely omit these lines.
=> istio: Avoid duplicate defaulthttpsettings within getIstioDestinationsAndSettingsMap

pkg/controller/should_process.go, pkg/worker/worker.go
Events from the `kube-system` namespace generate lots of log noise. This PR takes a rudimentary approach to limiting this.
Example:
```
I0729 18:09:11.537224   28650 worker.go:38] Skipping event: Skipping endpoints kube-system/kube-controller-manager as it is not used by any ingress
I0729 18:09:13.329869   28650 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0729 18:09:13.329894   28650 worker.go:38] Skipping event: Skipping endpoints kube-system/kube-scheduler as it is not used by any ingress
I0729 18:09:13.587406   28650 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0729 18:09:13.587446   28650 worker.go:38] Skipping event: Skipping endpoints kube-system/kube-controller-manager as it …
```
=> Ignore events from the kube-system namespace

dockerfiles/deploy.Dockerfile
Let's mark the binary as executable.
=> Dockerfile: mark /appgw-ingress as executable

pkg/controller/controller.go, pkg/worker/worker.go, pkg/worker/worker_test.go
It seems that we can simplify `worker.go` a bit.
This PR:
- removes `NewWorker()` - moves the struct initialization inline where `NewWorker()` was used - one place in production code (and one in tests)
- pulls the launching of a goroutine out of `worker.Run()` and into `controller.go` --> `go worker.Run()`
=> worker: Simplify

cmd/appgw-ingress/main.go
This is the first step to handling SIGINT and SIGTERM.
Within the current PR - this won't do much because `appGwIngressController.Start(env)` blocks forever, but that will be resolved in other PRs that are coming.
=> Handle SIGINT, SIGTERM

pkg/health/health.go
The goal of this is to create a service that responds to Kubernetes health-checking the AGIC pod.
Proposed endpoins:
- `/health/ready`
- `/health/alive`
Second part of this is coming in a PR shortly
=> health: Adding a health-probe service

pkg/appgw/backendhttpsettings.go, pkg/controller/prune.go, pkg/controller/prune_test.go, pkg/events/types.go
This PR allows to ignore ingresses that have ssl-redirect true but no TLS which is an valid configuration.
We cannot configure HTTPS for it and since, it was meant to have redirect for HTTP, we should nto configure HTTP for it.
=> prune redirect and no TLS ingresses

pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go
The previous implementation was incorrect. The `c.appGw.HTTPListeners` contained App Gwy config we fetched from ARM on the arrival of a new K8s event.
This PR introduces a new struct, which will be `nil` on the arrival of a new event when we instantiate a new `appGwConfigBuilder ` with `NewConfigBuilder()`
To provide more context on this change:
1. The loop that receives Kubernetes events and launches Process(Event) [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/worker/worker.go#L33)
2. for each event we do a GET on App Gwy's config [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/controller/process.go#L31)
3. we pass the original config appGw into the NewConfigBuilder …
=> Correct memoization of getListeners

pkg/appgw/health_probes.go
This PR removes * from the probe path. Probe path can have start when rule.path = `/xyz*`.
This causes the probe to fail.
=> fix: remove * from health probe path

pkg/controller/helpers.go, pkg/controller/helpers_test.go, pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go
This PR is a part of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/335
Removing this function as we will take simple approach just overriding the status.
=> delete removeIngressStatus and type for parse function

pkg/controller/controller.go, pkg/controller/process.go, pkg/controller/process_test.go, pkg/events/types.go
This PR updates the ingress status with appgw IP address.
Right now, AppGW either uses a public or a private ip, so the change is small.
For a more conplex scenario, we will store the map of front ip config to ip address and ingress resource to ip config.
=> feat: update ingress status with ip address

docs/annotations.md
All other examples use `test-ag` rather than `test-tag`, so I assume this is a typo.
=> Fix typo: test-tag --> test-ag

.pipelines/build.yml
This PR fixes 
1) build pipeline to build the binary with linker flag for version.
2) issue related to binary not being executable.
Before:
After:
=> fix: build binary with version arguments and chmod bin

cmd/appgw-ingress/main.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/certificates.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_ports.go, pkg/appgw/health_probes.go, pkg/appgw/redirects.go, pkg/appgw/requestroutingrules.go, pkg/appgw/types.go, pkg/controller/process.go, pkg/controller/prune.go, pkg/environment/environment.go, pkg/environment/environment_test.go, pkg/k8scontext/context.go, pkg/tests/fixtures.go
This PR simplifies the initialization of Feature Flags.
1) From the `ConfigBuilderContext ` struct - remove `EnableBrownfieldDeployment`, `EnableIstioIntegration`, and `EnablePanicOnPutError`
2) Convert environment variables `EnableBrownfieldDeployment `, `EnableIstioIntegration`, `EnableSaveConfigToFile`, `EnablePanicOnPutError` from `string` to `bool`
3) Use `GetEnvironmentVariable` to get env vars
=> Simplify feature flags; Move all to EnvVariables struct

cmd/appgw-ingress/main.go, cmd/appgw-ingress/main_test.go
In this PR - small tweaks to ensure that we retry `auth.NewAuthorizer...()` a few times before giving up. (Same as verifying the auth token)
- removed `initAppGwClient` - moved inline
- renamed `getAzAuth` to `getAuthorizer`
- carved `getAuthorizerWithRetry` out of `waitForAzureAuth`
- fixed a bug w/ checking Response codes - `panic: runtime error: invalid memory address or nil pointer dereference` is possible when there's no response (example: DNS failure / wrong hostname etc)
=> Retry getting auth token

pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/certificates.go, pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_ports.go, pkg/appgw/health_probes.go, pkg/appgw/ingress_rules.go, pkg/appgw/ingress_rules_test.go, pkg/appgw/istio_settings.go, pkg/appgw/redirects_test.go, pkg/appgw/requestroutingrules.go, pkg/tests/fixtures.go
This PR introduces more memoizations around often used functions.
In addition here we also attempt to increase readability and maintainability of code base, I'd like to introduce the alias `type Port int32`
This is primarily helpful in creating structures like `map[Port]interface{}`, which is arguably much more semantically clear (self explanatory) compared to `map[int32]interface{}`
Also in this PR - audaciously split `processIngressRules` in `getListenersFromIngress` and `getFrontendPortsFromIngress`
=> Memoize oft used functions; Use Port in lieu of int32

pkg/k8scontext/k8scontext_suite_test.go, pkg/k8scontext/k8scontext_test.go
This PR Improves test coverage.
Most significant change is renaming `k8scontext_test` package to `k8scontext`, which seems to have done in the first place due to collision of `Context` within `k8scontext` and `ginkgo`.  To avoid the redefinition - prefixing all ginkgo imports with the package name.
=> tests: Improve k8scontext tests

.pipelines/build.yml, cmd/appgw-ingress/main.go
```bash
VERSION github.com/Azure/application-gateway-kubernetes-ingress/pkg/version.Version:1.0.0-rc1, BUILD_DATE github.com/Azure/application-gateway-kubernetes-ingress/pkg/version.BuildDate:2019-08-29-01:29T+0000, GIT_HASH github.com/Azure/application-gateway-kubernetes-ingress/pkg/version.GitCommit:6bd98fd0
github.com/Azure/application-gateway-kubernetes-ingress/cmd/appgw-ingress
ERROR: logging before flag.Parse: I0829 01:29:25.305017   11870 main.go:291] Using verbosity level 1 from CLI flag verbosity
Version: 1.0.0-rc1; Commit: 6bd98fd0; Date: 2019-08-29-01:29T+0000
```
=> fix: missing repopath variable, move validateEnv

pkg/k8scontext/context.go, pkg/k8scontext/errors.go, pkg/k8scontext/handlers.go, pkg/k8scontext/k8scontext_suite_test.go, pkg/k8scontext/secretstore.go, pkg/k8scontext/secretstore_test.go
This PR tests `convertSecret`
In order to do that properly - changed the function signature so that it returns an `error` instead of a `bool`; added a few new error instances to our collection
This PR is the second piece of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/492
=> tests: Improve k8scontext.SecretStore test coverage

pkg/appgw/appgw_test.go, pkg/controller/controller.go, pkg/k8scontext/context.go, pkg/k8scontext/handlers.go, pkg/k8scontext/ingress_handlers.go, pkg/k8scontext/k8scontext_test.go, pkg/k8scontext/secrets_handlers.go, pkg/k8scontext/types.go, pkg/worker/worker.go, pkg/worker/worker_test.go
Removing our dependency on the RingChannel and using a buffered channel, typed specifically to the `Event` struct.
Initial concern with using the RingChannel was that we could potentially lose events.
Given that we always construct App Gateway config from scratch (and not using cumulative updates), this would have not been an issues (dropping events).
=> Remove RingChannel in lieu of a goode olde buffered channel

pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendaddresspools_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/backendhttpsettings_test.go, pkg/appgw/identifier.go, pkg/appgw/internaltypes.go, pkg/appgw/istio_pools.go, pkg/appgw/istio_routing_rules.go, pkg/appgw/istio_settings.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/appgw/types.go, pkg/controller/process.go
This PR adds `DefaultAddressPoolD` and `DefaultHTTPSettingsID` fields to `ConfigBuilderContext` in preparation for these being used in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/501
=> Adding DefaultAddressPooID and DefaultHTTPSettingsID fields to ConfigBuilderContext

pkg/controller/should_process.go, pkg/k8scontext/context.go, pkg/worker/fake.go, pkg/worker/types.go, pkg/worker/worker.go
At log level 5 we generate log lines that provide little to no value.
Example:
```
I0903 16:23:29.852755   22730 context.go:289] Service default/aad-pod-identity-mic does not exist
I0903 16:23:29.852793   22730 worker.go:27] Skipping event. Reason: endpoint default/aad-pod-identity-mic is not used by any Ingress
```
These messages could be valuable to help understand why certain backends are not created. In the current state these are being emitted too often. I'm moving these to log level 9 (for dev purposes only) and will continue to iterate on a solution to surface this, but in less noisy and repetitive way.
This PR fixes issue https://github.com/Azure/application-gateway-kubernetes-ingress/issues/505
=> Lower the amount of Idle logs

pkg/appgw/public_and_private_ip_test.go
This PR adds a false negative test, which reproduces a big where when Public and Private IP addresses are used - we create duplicate routing rules ("rr-80" in the example below).
This causes an ARM error: 
```
F0904 12:14:11.809485   11311 process.go:147] Failed applying App Gwy configuration: network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"DuplicateResourceName","message":"Resource /subscriptions//resourceGroups//providers/Microsoft.Network/applicationGateways/ has two child resources with the same name (rr-80)."}] -- {
```
This PR is the part one (of 2) to fixing issue https://github.com/Azure/application-gateway-kubernetes-ingress/issues/511
The …
=> False negative test on Public and Private Ingress Resources together

pkg/k8scontext/ingress_handlers.go, pkg/k8scontext/secrets_handlers.go, pkg/k8scontext/secretstore.go, pkg/k8scontext/secretstore_test.go
This PR renames `convertSecret` to `ConvertSecret`, which makes it accessible by external entities, and allows easier unit test setup.
=> Export k8scontext convertSecret function

pkg/controller/controller.go, pkg/events/events.go, pkg/k8scontext/handlers.go, pkg/k8scontext/ingress_handlers.go, pkg/k8scontext/secrets_handlers.go, pkg/k8scontext/types.go, pkg/worker/worker.go, pkg/worker/worker_test.go
This PR introduces a new function - `drainChan()`
The goal is to always work on the very last event within our buffered channel.
This is acceptable, since the Ingress Controller always queries for the Ingress, Service, Endpoints etc. and does not need the entire chain of events.
This will prevent overwhelming ARM with too many consecutive PUTs when the channel fills up quicker than ARM can apply config.
=> Drain the Work channel; Use the last event only

pkg/appgw/backendhttpsettings.go
It is possible to get in a situation where some pods are in Pending state, hence we cant find resolve here - and the `unresolvedBackendID` below has non-zero length.
The ingress controller should not break in this situation. There are already plenty of logs around this issue. Adding one more warning and continue.
=> Do not break on unresolved backends

pkg/k8scontext/errors.go
Adding error codes to each error message so that these can be referenced by documentation and automation.
The format chosen is:
- append to the end
- wrap in `(parenthesis)`
- first 4 characters indicate the namespace of the error
- last 3 characters is a zero-padded integer
=> k8scontext: Adding error codes

pkg/annotations/errors.go, pkg/annotations/errors_test.go, pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go, pkg/appgw/backendhttpsettings.go, pkg/controller/prune.go
Since `pkg/errors/errors.go` is used primarily for `pkg/annotations/errors.go` it would make sense to move it closer to where it used.
=> Moving errors/errors.go -> annotations/errors.go

pkg/appgw/health_probes.go, pkg/appgw/health_probes_test.go, pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go, pkg/tests/fixtures.go
In this PR we:
-- fix a bug, where for an Ingress resource with no Rules we panic (pkg/appgw/health_probes.go)
-- refactor `ListHTTPIngresses` so it is easier to test
-- add a new fixture with the simplest possible Ingress -- most importantly - no **Rules**
```yaml
---
kind: Ingress
metadata:
name: websocket-ingress
annotations:
kubernetes.io/ingress.class: azure/application-gateway
spec:
backend:
serviceName: websocket-service
servicePort: 80
---
```
=> Test with an Ingress with no Rules

docs/annotations.md
This PR adds documentation for `appgw.ingress.kubernetes.io/backend-protocol` annotation.
=> docs: annotation backend protocol

helm/ingress-azure/templates/clusterrole.yaml
We introduced a functionality which queries K8s nodes.
For RBAC clusters this requires we allow for AGIC to query `nodes`.
This PR fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/566
=> rbac: Allow for AGIC to query k8s nodes

pkg/appgw/backendaddresspools.go, pkg/appgw/configbuilder_test.go, pkg/appgw/requestroutingrules.go
This change will add a missing piece in AGIC so that it can properly configure App Gateway for the simplest possible Ingress resource:
```yaml
kind: Ingress
metadata:
name: aspnetapp
annotations:
kubernetes.io/ingress.class: azure/application-gateway
spec:
backend:
serviceName: aspnetapp
servicePort: 80
```
=> Handle Ingress w/ no Rules (simplest Ingress YAML)

pkg/appgw/configbuilder_test.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/identifier.go, pkg/appgw/public_and_private_ip_test.go
When we create IDs for certain resources we capitalize the `E`
App Gateway (or ARM) corrects that automatically.
This results in a difference between the config we create and the config we get from App Gwy.
`frontendPorts` (App Gateway) vs `frontEndPorts` (AGIC)
`frontendIPConfigurations` (App Gateway) vs `frontEndIPConfigurations` (AGIC)
```json
-- Existing App Gwy Config --        "httpListeners": [
-- Existing App Gwy Config --            {
-- Existing App Gwy Config --                "etag": "W/\"aaa\"",
-- Existing App Gwy Config --                "id": "/subscriptions/aaa/resourceGroups/derayche-rg-A/providers/Microsoft.Network/applicationGateways/applicationgatewayd0f0/httpListeners/fl-80",
-- Existing App Gwy Config --                "name": "fl-80",
-- Existing App Gwy Config -- …
```
=> Correcting a typo in the naming of frontendPorts resources

cmd/appgw-ingress/main.go, helm/ingress-azure/templates/deployment.yaml, pkg/appgw/configbuilder.go, pkg/azure/azure_test.go, pkg/azure/context.go, pkg/environment/environment.go
This PR adds the code to mount the azure.json file and fill out the az context data struct.
This context will provide us with credentials and vnet details.
Following PR will be about using this.
Sample azure.json
```json
{
"cloud": "xxxx",
"tenantId": "t",
"subscriptionId": "s",
"aadClientId": "c",
"aadClientSecret": "cs",
"resourceGroup": "r",
"location": "l",
"vmType": "xxxx",
"subnetName": "xxxx",
"securityGroupName": "xxxx",
"vnetName": "xxxx",
"vnetResourceGroup": "xxxx",
"routeTableName": "xxxx",
"primaryAvailabilitySetName": "xxxx",
"primaryScaleSetName": "xxxx",
"cloudProviderBackoff": "xxxx",
"cloudProviderBackoffRetries": "xxxx",
"cloudProviderBackoffExponent": "xxxx",
"cloudProviderBackoffDuration": "xxxx",
"cloudProviderBackoffJitter": "xxxx",
"cloudProviderRatelimit": "xxxx", …
```
=> azcontext: mount azure.json and file out azcontext

helm/ingress-azure/values-template.yaml, helm/release.sh
```bash
./release.sh 0.9.0-test https://repo bad
- tagging with [0.9.0-test]
- exiting bad/unknown environment provided:  bad
```
Prod using mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
```bash
./release.sh 0.9.0-test https://repo prod
- tagging with [0.9.0-test]
- deployment will use registry:  mcr.microsoft.com/azure-application-gateway/kubernetes-ingress
- update helm templates
- running helm package
Successfully packaged chart and saved it to: /c/Users/aksgupta/go/src/github.com/Azure/application-gateway-kubernetes-ingress/helm/ingress-azure-0.9.0-test.tgz
- check if helm index [https://repo/index.yaml] exists in helm repo [https://repo]
```
Staging using mcr.microsoft.com/azure-application-gateway/kubernetes-ingress-staging
```bash
./release.sh 0.9.0-test …
```
=> pipeline: modify registry based in env- prod,staging

cmd/appgw-ingress/main.go, helm/ingress-azure/templates/NOTES.txt, helm/ingress-azure/templates/aadpodidbinding.yaml, helm/ingress-azure/templates/aadpodidentity.yaml, helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/templates/deployment.yaml, pkg/azure/auth.go, pkg/azure/azure_test.go, pkg/environment/environment.go
This PR modifies the authorization section.
We now have three sources of authorizations:
1) through a Auth File aka Service Principal
2) through a Managed Identity
3) through AzContext
4) Fall back to whatever is configured on the environment
Also, when user specifies a managed identity (uses AAD Pod Identity), there is no straight way for us to know if they using managed identity, so added a new environment variable.
=> auth: use AzContext for auth and add env variable for Managed Identity

pkg/controller/should_process.go
The goal of this PR is to ignore events coming from `default/aad-pod-identity-mic` so the logs are a bit cleaner.
=> Ignore AAD Pod Identity events and logs

pkg/k8scontext/context.go, pkg/sorter/ingress.go
This PR switches sorting of Ingress resources from UID, to Name for more predictability within unit tests.
=> Sort ingresses by Namespace/Name

pkg/appgw/requestroutingrules.go
This PR fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/571
=> Set Backend and HTTP Settings to nil when Redirect is configured

functional_tests/functional_test.go, functional_tests/three_ingresses.json, pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools_test.go, pkg/appgw/backendhttpsettings_test.go, pkg/appgw/configbuilder_test.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/health_probes_test.go, pkg/appgw/ingress_rules_test.go, pkg/appgw/public_and_private_ip_test.go, pkg/appgw/redirects_test.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/appgw/types_test.go, pkg/controller/process_test.go, pkg/controller/prune_test.go
This change ensures that once the Default Backend has been set to something that has been derived from a Kubernetes Service it is **not** overwritten with a subsequent Ingress Resourc and set to the default empty backend pool.
This PR fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/580
=> bug: Do not overwrite service specific default backend pool

functional_tests/functional_test.go, functional_tests/helpers.go, functional_tests/one_ingress_slash_nothing.json, functional_tests/one_ingress_slash_slashnothing.json, functional_tests/run.sh, functional_tests/three_ingresses.json, functional_tests/two_ingresses_same_domain_tls_notls.json, functional_tests/two_ingresses_slash_slashsomething.json
These are the (semantically incompatible) tests for https://github.com/Azure/application-gateway-kubernetes-ingress/pull/591
These tests cover https://github.com/Azure/application-gateway-kubernetes-ingress/issues/571
I corrected the warming up of the secrets cache (and added proper secrets), which enabled TLS for these tests, hence the larger than expected changes.
The new addition to the test suite is `functional_tests/two_ingresses_same_domain_tls_notls.json`  and the https://github.com/Azure/application-gateway-kubernetes-ingress/compare/draychev/fix-sslredirect?expand=1#diff-f184c6b27beefd59b48cbee1236306efR502
=> More functional tests covering two Ingress resources

docs/setup/install-new.md
#594
The yaml in bash toward the bottom of this document was being rendered incorrectly on the docs site. I changed the style to be in line with [your websockets page](https://azure.github.io/application-gateway-kubernetes-ingress/how-tos/websockets/) which renders it correctly. 
Also the indentation under [Install AAD Pod Identity](https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-new/#install-aad-pod-identity) had the bulleted list being rendered as a code block.
=> fix GH markdown causing rendering bug

pkg/appgw/frontend_listeners.go, pkg/appgw/requestroutingrules.go
It is time to use `GetBlacklistedPorts()`, `LogPorts()`, and `MergePorts()` to properly preserve Frontend Ports covered by a `AzureIngressProhibitedTarget` CRD
Part 2: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/578/files
=> brownfield: Merge Ports

pkg/appgw/backendaddresspools.go, pkg/appgw/backendaddresspools_test.go
Fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/606
Endpoints have two set of IP addresses in `Addresses` and `NotReadyAddresses` list. These are updated as the readiness Probe becomes healthy and unhealthy to fully utilize the gateway's probing.
=> fix: add not ready address endpoints to Backend pool

cmd/appgw-ingress/main.go, functional_tests/functional_test.go, pkg/appgw/appgw_test.go, pkg/appgw/configbuilder_test.go, pkg/appgw/public_and_private_ip_test.go, pkg/controller/controller.go, pkg/controller/process.go, pkg/controller/process_test.go, pkg/k8scontext/context.go, pkg/k8scontext/handlers.go, pkg/k8scontext/ingress_handlers.go, pkg/k8scontext/ingress_handlers_test.go, pkg/k8scontext/k8scontext_test.go, pkg/k8scontext/secrets_handlers.go, pkg/k8scontext/secrets_handlers_test.go, pkg/k8scontext/types.go, pkg/metricstore/fake.go, pkg/metricstore/metricstore.go
This PR adds more metrics to metric server
1. `k8s_api_event_counter`
1. `arm_api_call_counter`
1. `arm_api_update_call_failure_counter`
1. `arm_api_update_call_success_counter`
=> metrics: add more metrics for Prometheus metric server

scripts/start.sh
This PR removes `GOOS`, some of the extra coloring and also catches up the start script to the latest code base.
=> Remove GOOS from scripts/start.sh

cmd/appgw-ingress/main.go, helm/ingress-azure/templates/configmap.yaml, pkg/azure/client.go, pkg/azure/fake.go, pkg/environment/environment.go
This PR adds new parameters to the helm config.
1. `applicationGatewayID`
1. `subnetPrefix`
1. `subnetName`
Add new validations:
1. Either `applicationGatewayID` or `name` should be given.
1. When `applicationGatewayID`, it is bring your own appgw case.
1. When appgw's `name` is used, then we assume that it is a create case. We ask for either `subnetID` or `subnetPrefix`.
=> deploy: deploy subnet when subnet prefix is given

helm/ingress-azure/templates/deployment.yaml
The incorrect indentation is causing `mapping values are not allowed in this context`
This PR fixes the immediate problem.
With another PR I will introduce tests to ensure this is covered.
=> helm: Fixing ARM template

functional_tests/functional_test.go, functional_tests/one_ingress_slash_nothing.json, functional_tests/one_ingress_slash_slashnothing.json, functional_tests/three_ingresses.json, functional_tests/two_ingresses_same_domain_tls_notls.json, functional_tests/two_ingresses_slash_slashsomething.json, go.mod, go.sum, pkg/appgw/appgw_test.go, pkg/appgw/configbuilder.go, pkg/appgw/configbuilder_test.go, pkg/appgw/public_and_private_ip_test.go, pkg/azure/tags/consts.go, pkg/controller/process.go, pkg/k8scontext/k8scontext_test.go, pkg/tests/mocks/clock.go
A very handy tool when troubleshooting App Gateway - AGIC - AKS issues would be a time stamp of the last configuration applied to App Gateway.
What it looks like in the JSON config:
```json
"last-updated-by-k8s-ingress": "2019-09-26 15:01:44.7357874 -0700 PDT m=+2.198648801",
```
What this looks like on [portal](https://portal.azure.com):
=> Adding a new User Tag to App Gateway with the Last Update from AGIC

pkg/azure/client.go, pkg/controller/mutate_aks.go, pkg/controller/mutate_aks_test.go, pkg/controller/mutate_app_gateway.go, pkg/controller/mutate_app_gateway_test.go, pkg/controller/prune_test.go, pkg/k8scontext/context.go, pkg/worker/fake.go, pkg/worker/types.go, pkg/worker/worker.go, pkg/worker/worker_test.go
In this PR:
- fleshing out `MutateAKS` -- runs for any kubernetes event
- added memoization to `GetPublicIP` - so that once an IP resource URI has been resolved to an IP address we don't have to do lookups again.
- added error handling to the `AddToUserAgent` invocations
- I deliberately chose to remove the following block:
```go
if !k8scontext.IsIngressApplicationGateway(ingress) || !cbCtx.InIngressList(ingress) {
if err := c.k8sContext.UpdateIngressStatus(*ingress, ""); err != nil {
```
The concern with the block above is that AGIC will be wiping the IP address of Ingress resources that it should not (no longer) be concerned with.  So if I have an Nginx ingress it seems that AGIC here will mutate that as well.  The downsides is that with the block of code removed we may leave previously …
=> Simplify Updating ingress IP address; Do only if new IP

docs/how-tos/lets-encrypt.md
Updating documentation of Let's Encrypt / Cert-Manager for latest release of the software.
Source: https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme/index.html
Fixes: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/602
=> Updating LetsEncrypt documentation for v0.11 of Cert-Manager

pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_listeners_istio.go, pkg/brownfield/ports.go
This PR moves code from `pkg/appgw/frontend_listeners.go` into (new) `pkg/appgw/frontend_listeners_istio.go` to simplify the code in frontend_listeners.
There are no functional code changes in this PR.
=> istio: Carve out istio port generation to simplify frontend_listeners.go

pkg/azure/client.go
This PR modifies the subnet look up.
Earlier, we were looking for existing subnet by matching address prefix provided in `subnetPrefix` parameter. We were not matching the `subnetName` parameter.
=> fix: use subnet name in subnet lookup

functional_tests/functional_test.go, functional_tests/waf_annotation.json, pkg/annotations/ingress_annotations.go, pkg/appgw/requestroutingrules.go
In this PR we attach an Azure Firewall Policy to an App Gateway, per path, from an Ingress annotation.
- recognize the `/waf-policy-for-path` Ingress annotation
- attach the WAF policy from the key of the annotation to each path rule
(notice the `firewallPolicy` key)
```json
"urlPathMaps": [
{
"id": "/subscriptions/xxx/resourceGroups/rg/providers/Microsoft.Network/applicationGateways/applicationgatewayd0f0/urlPathMaps/url-www.contoso.com-443",
"name": "url-www.contoso.com-443",
"properties": {
"defaultBackendAddressPool": {
"id": "/subscriptions/xxx/resourceGroups/rg/providers/Microsoft.Network/applicationGateways/applicationgatewayd0f0/backendAddressPools/defaultaddresspool"
},
"defaultBackendHttpSettings": {
"id": "/subscriptions/xxx/resourceGroups/rg/providers/Microsoft.Network/applicat …
```
=> ingress: Adding annotation waf-policy-for-path; Attach policy to path rule

docs/setup/install-existing.md
This PR fixed a part of "Brownfield Deployment" document. 
`--subscription` option of `az ad sp create-for-rbac` is not supported now.
https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest
=> Removed unsupported '--subscription' option

pkg/controller/helpers.go
With the addition of the `last-updated-by-k8s-ingress` tag via https://github.com/Azure/application-gateway-kubernetes-ingress/pull/561 we introduced a subtle (or not so) cache buster.
To ensure that we could cache, and correctly identify JSON configs that have not changed since last ARM PUT, we remove the UserTags field - much like we do with etags.
Cache buster in question:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/0.10.0/pkg/appgw/configbuilder.go#L213
Tested:
```
I1030 17:20:04.354645   23852 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
```
=> Remove Tags field before caching config

helm/ingress-azure/templates/deployment.yaml, pkg/metricstore/metricstore.go
This PR adds annotations to the AGIC pod deployments. This will be used by prometheus to discover metrics from AGIC. Also, adding registering the new metrics.
=> prometheus: add prom annot for deployment and register newly metrics

cmd/appgw-ingress/main.go, pkg/appgw/configbuilder.go, pkg/events/types.go
With this PR we discontinue support of v1 of App Gateway.
The proposed commit will print the following whet App Gateway is of the supported set of SKU Tiers:
```
F1030 14:26:42.482820   17255 main.go:197] App Gateway SKU Tier Standard is not supported by AGIC version 0.11.0/2f8cb7f5/2019-10-30-14:26T-0700
```
The addition of `time.Sleep` for 5 seconds is deliberate - to slow down the cycling of the AGIC pod.
=> Break on old App Gateway SKUs

helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/templates/deployment.yaml, pkg/appgw/frontend_listeners.go, pkg/appgw/internaltypes.go, pkg/environment/environment.go
This PR stacked on top of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/644 -- adds FirewallPolicy to the Listener, when there are no rules.
- adding `ATTACH_WAF_POLICY_TO_LISTENER` variable to enable attaching WAF policy to listener
- adding `FirewallPolicy` to the `listenerAzConfig` struct
- when `AttachWAFPolicyToListener` is enabled - attach policy to respective listener
- for default listener - find an Ingress with a WAF annotation and attach it to the only listener
=> Attach a FirewallPolicy to the listener w/ a feature flag

README.md, docs/how-tos/dns.md, docs/tutorial.md
Adding a section, which describes how AGIC can be integrated with https://github.com/kubernetes-sigs/external-dns to achieve automatic DNS updates based on the hostname of the Ingress resource and the Public IP address of App Gateway.
Also in this PR: moving the list of How-to docs one level higher into the README.  I think this list is great - it showcases the cool things AGIC can do.  It'd be good to have that on the front page. (And we should continue to expand it)
=> tutorials: Adding a tutorial on Automating DNS updates

functional_tests/functional_test.go, functional_tests/health_probes_same_labels_different_namespaces.json, pkg/tests/fixtures.go
This functional test covers https://github.com/Azure/application-gateway-kubernetes-ingress/pull/658 and https://github.com/Azure/application-gateway-kubernetes-ingress/pull/616
The test will be breaking until https://github.com/Azure/application-gateway-kubernetes-ingress/pull/658 is merged
=> Adding a functional test for Health Probes on pods w/ same labels but different namespaces

helm/ingress-azure/Chart.yaml, helm/ingress-azure/templates/NOTES.txt, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml, scripts/install-without-tiller.sh
This PR adds a script that show how we can install AGIC using Helm 3, but without having Tiller on the cluster.
Also providing defaults for `usePrivateIP`, which is needed for Helm 3.
Fixes:  https://github.com/Azure/application-gateway-kubernetes-ingress/issues/664
=> helm: script to install w/ Helm but w/o Tiller; default for usePrivateIP

cmd/appgw-ingress/main.go, helm/ingress-azure/templates/deployment.yaml, pkg/azure/client.go, pkg/azure/fake.go
[UPDATE]: As issue here is with waiting for AAD pod identity to provide a token and then becoming live. This causes AGIC to get terminated when token process takes longer.
To avoid this, We have decided to start the http server before the token process. This will make the pod `live` from k8s perspective. Readiness probe will still rely on cache sync channel to close to indicate that controller is ready.
[OLD] We know that AAD Pod Identity in its current form may take 10 to 15 minutes to start. 
Issue https://github.com/Azure/application-gateway-kubernetes-ingress/issues/668 is a manifestation of this delay.
Our Readiness and Liveness probes are aggressive - defaulted to `failureThreshold` of 3.
That makes readiness crash after 30 seconds and liveness after 60 seconds.
This PR increases …
=> probes: start http server for liveness early on

cmd/appgw-ingress/main.go, pkg/azure/azure.go, pkg/azure/azure_test.go, pkg/azure/client.go, pkg/azure/context.go, pkg/azure/fake.go
This PR allows AGIC to associate AKS cluster's route table to AppGW's subnet, This is required for supporting kubenet which uses route table for routing.
We extract the route table name from `azure.json` mounted through the node and then check for it's existence.
If it exists, then if appgw subnet has a route table already, we skip the assignment, else we update the subnet with the route table.
We perform these checks as best effort. If any of these fail, we simply move forward after logging error.
* If route table is not found, following is the error message:
```
I0127 16:06:08.530284   32437 client.go:190] Error getting route table '/subscriptions/xxxx/resourceGroups/resgp/providers/Microsoft.Network/routeTables/aks-agentpool-10660215-routetable1' (this is relevant for AKS clusters …
```
=> kubenet: associate route table to appgw subnet

deploy/azuredeploy.json
This PR removes the addon profile from the aks resource definition as it is not needed any more.
=> template: remove addonProfiles from deployment yaml

cmd/appgw-ingress/main.go, cmd/appgw-ingress/utils.go, pkg/azure/context.go, pkg/environment/environment.go
This PR aims at cleaning up main.go.
1. move helper functions to a different file.
1. add function consolidating the env variable; setup defaults and use azContext.
=> chore: consolidate env and move helper functions to utils.go

cmd/appgw-ingress/main.go, helm/ingress-azure/templates/deployment.yaml, pkg/azure/auth.go, pkg/azure/azure_test.go, pkg/azure/cloudproviderconfig.go, pkg/environment/environment.go
This PR simply renames the AzContext to CloudProviderConfig.
**About CloudProviderConfig:**
CloudProviderConfig is standard file configuration file used by cloud provider as an input to the cloud controller manager. It is present on every node. We use this file to get information about node resource group's subscriptionID, resource group name, vnet/route table information.
We use this file if it present and mounted to the pod.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md
```json
{
"cloud": "xxxx",
"tenantId": "t",
"subscriptionId": "s",
"aadClientId": "c",
"aadClientSecret": "cs",
"resourceGroup": "r",
"location": "l",
"vmType": "xxxx",
"subnetName": "xxxx",
"securityGroupName": "xxxx",
"vnetName": "xxxx",
"vnetResourceGroup": "xxxx", …
```
=> chore: rename AzContext to CloudProviderConfig

pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/backendhttpsettings_test.go, pkg/appgw/health_probes.go, pkg/appgw/identifier.go, pkg/controller/prune.go, pkg/controller/prune_test.go, pkg/events/types.go, pkg/tests/fixtures/app_gateway.go, pkg/tests/fixtures/certificates.go
Add a new annotation, appgw-trusted-root-certificate. The new annotation allows to whitelist appgw pre-installed root certificate(s) used by end-to-end ssl encryption. The new annotation should be used together with backend protocal annotation, https specifically
=> Add a new annotation, appgw-trusted-root-certificate. 

functional_tests/health_probes_same_labels_different_namespaces.json, functional_tests/one_ingress_slash_slashnothing.json, functional_tests/three_ingresses.json, functional_tests/two_ingresses_same_domain_tls_notls.json, functional_tests/two_ingresses_same_hostname_value_different_locations.json, functional_tests/two_ingresses_slash_slashsomething.json, functional_tests/two_ingresses_with_and_without_extended_hostname.json, functional_tests/waf_annotation.json, pkg/appgw/backendaddresspools_test.go, pkg/appgw/certificates.go, pkg/appgw/identifier.go, pkg/appgw/istio_routing_rules.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go
This PR sets the resource ID for path rules in url path map. Also, performed refactoring and ignoring location and resource guid when comparing input gateway with cached gateway.
=> fix: assign resource ID to path rule; refactor other assignments; ignore resource guid and location

deploy/azuredeploy.json
Currently, when trying to run the ARM template it throws an error due to incorrect kubernetes version.
The correct version is 1.15.10
=> version: update k8s version

pkg/appgw/appgw_test.go, pkg/appgw/health_probes.go
a) This PR uses the backend hostname annotation to set the host in probe.
So, in order of priority, here is how properties for probe are selected:
1) Readiness Probe
2) Liveness Probe
3) backend-prefixed Annotations
4) ingress.rules for host and path
b) This PR also fixes a small issue in translating liveness and readiness probes.
Fixes: #789
=> probe: set hostname based on backend hostname if provided; respect readiness/livesness scheme fix

docs/features/appgw-ssl-certificate.md
Since it's a managed identity, the field `principalId` should be used.
=> doc: Correct the field used for identityPrincipal

.pipelines/build.yml, cmd/appgw-ingress/main_test.go, functional_tests/functional_test.go, pkg/annotations/errors.go, pkg/annotations/errors_test.go, pkg/annotations/ingress_annotations_test.go, pkg/appgw/appgw_suite_test.go, pkg/appgw/identifier_test.go, pkg/azure/azure_test.go, pkg/brownfield/brownfield_suite_test.go, pkg/controller/controller_suite_test.go, pkg/environment/environment_test.go, pkg/k8scontext/k8scontext_suite_test.go, pkg/tests/fixtures/fixtures_suite_test.go, pkg/tests/fixtures_test.go, pkg/utils/utils_test.go, pkg/worker/worker_suite_test.go
This PR adds build tag `unittest` to all the unit tests and uses the tag in the `build.yaml` pipeline file.
=> pipeline: add unittest tag to test and modify pipeline to use tag

helm/ingress-azure/templates/aadpodidbinding.yaml, helm/ingress-azure/templates/aadpodidentity.yaml
This PR fix the casing in the AAD Pod identity CRDs created when using user assigned identity with AGIC.
This is to address the breaking change introduced in the AAD POD identity.
https://github.com/Azure/aad-pod-identity#v160-breaking-change
We create the AzureIdentity and AzureIdentityBinding resources.
Will go out in `1.2.0-rc2`.
Fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/823
=> fix: update the casing for aad-pod-identity crds

docs/setup/install-existing.md, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
This PR updates the install documentation to use the AAD Pod Identity v1.5.5 as the latest version in the master has a breaking change.
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/828
=> doc: update the instruction to use AAD Pod identity v1.5.5

docs/setup/install-existing.md, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
Fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/822
=> docs: update install instruction to use 1.2.0-rc1 when using k8s >= 1.16

crds/examples/AzureApplicationGatewayBackendPool.yaml, helm/ingress-azure/templates/deployment.yaml, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml
This PR removes the replicaCount parameter from helm config.
**Explanation**:
Right now, AGIC doesn't support leader election. When multiple replicas are created, all the `n` pods in the deployment will try to update the Application Gateway `n` times for each change in the cluster. This can cause an operation build up on the gateway and also, led to throttling by ARM.
=> helm: remove replicaCount parameter and set count to 1

functional_tests/functional_test.go, functional_tests/one_ingress_https_backend_without_backend_protocol.json, pkg/appgw/backendhttpsettings.go, pkg/appgw/backendhttpsettings_test.go, pkg/appgw/health_probes.go, pkg/k8scontext/context.go
This PR addresses two issues:
1) When a service uses port 443, this change will initialise the protocol to HTTPS by default. This behaviour can changed by using the backend-protocol annotation.
2) Fix for nil exception when looking for a service.
Fixes: #851, #779, #752, #635, #629
=> httpsetting to have https protocol in case port is at 443

scripts/e2e/cmd/runner/mfu_one_namespace_one_ingress_test.go, scripts/e2e/cmd/runner/testdata/one-namespace-one-ingress/container-readiness-probe/app.yaml, scripts/e2e/cmd/runner/testdata/one-namespace-one-ingress/container-readiness-probe/deploy.sh
- backend will be removed when health probe is unhealthy
-  appgw health probe is determined by the readiness probe defined in the container
=> e2e: add test case to test backend availability with health probing

docs/annotations.md, pkg/appgw/health_probes.go
When deploying Prometheus Operator on our cluster we run into the problem that the UnhealthyThreshold goes beyond 20 and the ingress controller gives an error: ApplicationGatewayProbeUnhealthyThresholdIsInvalid.
See: 
> error: network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayProbeUnhealthyThresholdIsInvalid" Message="Unhealthy threshold specified for Probe /subscriptions/.../resourceGroups/rg-gateway/providers/Microsoft.Network/applicationGateways/gateway/probes/pb-monitoring-mdf-prometheus-operator-prometheu-cc513868657fb3a5420b340c3bd9625c is not valid. Supported range is [0, 20]." Details=[]'
Currently the code just grabs the `FailureThreshold` from the Probe, but in the case of Prometheus we have no …
=> Added check to prevent UnhealthyThreshold to go beyond 20

docs/features/agic-reconcile.md
- [NA] If applicable, the changes made in the PR have proper test coverage
- [NA] Issues addressed by the PR are mentioned in the description followed by `Fixes`.
Added the acceptable values for ReconcilePeriodSeconds to the docs.
No issues raised but I set this to a value outside the acceptable range and it caused the pod to crash.
=> Add ReconcilePeriodSeconds parameters to docs page

pkg/brownfield/listeners.go, pkg/brownfield/listeners_test.go, pkg/brownfield/pathmaps_test.go, pkg/brownfield/routing_rules.go, pkg/brownfield/routing_rules_test.go, pkg/brownfield/targets_test.go, pkg/brownfield/types_test.go, pkg/tests/fixtures.go, pkg/tests/fixtures/app_gateway.go, pkg/tests/fixtures/listeners.go, pkg/tests/fixtures/paths.go, pkg/tests/fixtures/routing_rules.go, pkg/tests/fixtures/targets.go
This PR updates the brownfield workflow to use hostnames field from the HTTP listener in App Gateway for determining the blacklists.
I have tried to handle both hostName and HostNames in the HTTP listener to maintain backend compatibility.
=> brownfield: convert hostName to hostnames in brownfield

helm/ingress-azure/crds/azureingressprohibitedtarget.yaml, helm/ingress-azure/templates/crds.yaml
Now support to install crd by helm 2 as well as helm 3
hook: "crd-install will be unknown and skipped when helm3 is used
crd cannot be installed neither by helm 2 nor helm 3
=> support install crd by helm3

cmd/appgw-ingress/utils.go, pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go, pkg/environment/environment.go
This PR addresses the error when creating an event on ingress or pod object.
`no kind is registered for the type v1.Pod in scheme "pkg/runtime/scheme.go:101"`
The problem was due to using incorrect scheme. Scheme is used from the k8s package and the schemes coming from crd package are merged and provided to the recorder.
=> fix: correct the usage of scheme for recorder

docs/setup/install-existing.md
This PR fixes the identity section in the brownfield deployment steps.
The step were to create the identity in the node resource group and has a mistake in the following steps using the cluster's resource group.
Fixed this by only using the cluster's resource group for identity and adding the additional RBAC needed to make that work.
=> fix: identity creation and role assignment in brownfield deployment steps

docs/tutorials/tutorial.general.md
The docs linked for deployment are up one directory.
Links updated to match the location of the files referenced
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>
Clicking the links for deployment led to a Github 404 page or, if looking at the MkDocs site, a style-less 404.
Updated the link destination to use the (relative) parent directory to match where the files are located in the repository
No issue related to the links were found when searching the term "deployment" in the issues
=> docs: Update deployment links in tutorial.general

docs/helm-values-documenation.md, helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml
When work with agic in shared mode, is a normal scenario when you have 2 or more environment behind the same agw and promote from one to the next (dev -> uat -> prod).  In this case, the namespaces and services have the same naming, so all the agw internal resources are in conflict between them in the different environments. 
Agic supports the use of prefix that is added in each resource but that setting is not editable using helm. 
This PR added support to manage the prefix in order to allow share the same agw between different clusters those have the same application in different environments.
#957
=> Added binding for APPGW_CONFIG_NAME_PREFIX in helm chart

.pipelines/build.yml, helm/ingress-azure/templates/configmap.yaml
As @rbickel mentioned in the commit, https://github.com/Azure/application-gateway-kubernetes-ingress/commit/b3464c9a540aa03984fa8be1347769ac1d788f2c#r41249662,  I introduced an error that breaks the chart. 
This PR fix the broken chart and add a task during the integration to lint the chart in order to detect errors  before the merge and to block it.
https://github.com/Azure/application-gateway-kubernetes-ingress/commit/b3464c9a540aa03984fa8be1347769ac1d788f2c#r41249662
=> Fixed broken chart and added a check for helm chart during the integration

functional_tests/functional_test.go, functional_tests/health_probes_same_labels_different_namespaces.json, functional_tests/one_ingress_https_backend.json, functional_tests/one_ingress_https_backend_without_backend_protocol.json, functional_tests/one_ingress_slash_nothing.json, functional_tests/one_ingress_slash_slashnothing.json, functional_tests/one_ingress_with_multiple_path_rules.json, functional_tests/three_ingresses.json, functional_tests/two_ingresses_same_domain_tls_notls.json, functional_tests/two_ingresses_same_hostname_value_different_locations.json, functional_tests/two_ingresses_slash_slashsomething.json, functional_tests/waf_annotation.json, pkg/appgw/internaltypes.go, pkg/appgw/istio_routing_rules.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/k8scontext/context.go
This PR fixes a bug in the naming of the path rules in the URL path maps in the Application Gateway config. This was reported as bug in an CRI.
Currently, when an ingress contains multiple ingress rules but with same `host`, the paths are merged into the same URL path map but with the same name which causes the validation to fail on the gateway.
**Example**
```yaml
kind: Ingress
metadata:
name: aspnetapp
annotations:
appgw.ingress.kubernetes.io/backend-path-prefix: "/"
kubernetes.io/ingress.class: azure/application-gateway
spec:
rules:
- http:
paths:
- path: "/picking/*"
backend:
serviceName: aspnetapp
servicePort: 80
- http:
paths:
- path: "/loading/*"
backend:
serviceName: aspnetapp2
servicePort: 80
```
**Error**
`error: …
=> fix: duplicate URL Path Map names w/ certain Ingress YAML

docs/how-tos/minimize-downtime-during-deployments.md
With the timeout command I got the next error:
`Exec lifecycle hook ([timeout 90]) for Container "<pod-name>" in Pod "<pod-name>-8654f6d665-wnwk7_universidades(e0af2c47-c900-4d35-9209-7723fcc3681b)" failed - error: command 'timeout 90' exited with 1: ERROR: Input redirection is not supported, exiting the process immediately.
, message: "ERROR: Input redirection is not supported, exiting the process immediately.\r\n"`
None
=> docs: Update Windows containers equivalent sleep command

pkg/appgw/backendhttpsettings.go, pkg/appgw/backendhttpsettings_test.go, pkg/tests/fixtures.go
Updating logic to choose single backend port in case backend port name is resolved to multiple backend ports retrieved by endpoints
Currently, if service target endpoint is not provided, endpoints api is called to see what are the backend ports and in case multiple backend ports exists with same name, AGIC stops processing the update and PUT will not be issued to AppGw. Only way to fix this problem is deleting the ingress which lead to this problem.
After this changes, in case there are multiple target backend ports, smallest backend port is chosen to create backend http settings.
Currently, if service target endpoint is not provided, endpoints api is called to see what are the backend ports and in case multiple backend ports exists with same name, AGIC stops processing the update and PUT …
=> fix: choose backend port in case backend port name is resolved to multiple backend ports

docs/setup/install-existing.md
(not applicable)
(also not applicable)
The file in question, [`docs/examples/sample-helm-config.yaml`][^1], uses camelCase for these pseudo-variables.
**Alternatively**, the `sample-helm-config.yaml` could be updated to match the kebab-case used in the documentation. I assume the change I made is what's intended, but I absolutely don't have a strong opinion. I just noticed a minor inconsistency while following the docs and figured I could contribute a fix. 🙂
[^1]: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/762b7fd2a1bc9058be55d5dec6159409e98877ff/docs/examples/sample-helm-config.yaml
(Not applicable)
=> Minor clarification to documentation, fixing references to match the actual variables’ casing convention

helm/ingress-azure/templates/deployment.yaml
This PR adjusts the security context so that AGIC pod has access to azure.json.
Since, azure.json is used get vnet/route table/service principal information.
Figure out a better way to find this information without being root user.
[E2E run](https://dev.azure.com/azure/application-gateway-kubernetes-ingress/_releaseProgress?_a=release-environment-extension&releaseId=417&environmentId=911&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab)
=> fix: adjust security context to maintain access to azure.json

helm/ingress-azure/templates/configmap.yaml
This PR moves subResourceNamePrefix out of the `if/else` block for `appgw resource ID` vs `appgw name`. It was found when the e2e failed.
=> fix: correct position of subResourceNamePrefix in configmap

helm/ingress-azure/templates/configmap.yaml, scripts/e2e/helm-config-with-prohibited-rules.yaml, scripts/e2e/helper.sh
This PR adds e2e for 2 cases:
1. Use the new helm config way of adding prohibited target
2. Make sure that AGIC is able to use azure.json by just providing gateway name and no other information. AGIC should get remaining info from azure.json.
=> e2e: prohibited using helm, use azure.json

scripts/e2e/cmd/runner/helper.go, scripts/e2e/cmd/runner/mfu_one_namespace_one_ingress_test.go, scripts/e2e/cmd/runner/testdata/one-namespace-one-ingress/invalid-configuration/app.yaml, scripts/e2e/cmd/runner/testdata/one-namespace-one-ingress/override-frontend-port/app.yaml
This PR adds e2e for two cases:
1. Test out the override-frontend port annotation and make a request at that port
2. Test the fixes for configuration reliability
a. when ingress contains duplicate paths.
b. when ingress contains multiple rules with multiple paths. This was failing before due to conflicting naming.
c. when two pods in a service different container ports causing conflicts.
=> e2e: override-frontend-port, duplicate path and multiple url path maps

scripts/e2e/cmd/runner/environment.go, scripts/e2e/cmd/runner/helper.go, scripts/e2e/cmd/runner/lfu_one_namespace_one_ingress_test.go, scripts/e2e/helper.sh
This PR adds
1. fixes a bug in the placement of subResourceNamePrefix in the helm config.
2. an e2e that uses subResourceNamePrefix in the helm and validates that app gateway sub-resources are named apt-ly.
=> e2e: validate subResourceNamePrefix is used to name appgw sub-resources

docs/annotations.md, pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go, pkg/appgw/health_probes.go, pkg/appgw/health_probes_test.go
It expands list of recognized ingress annotations with following additions:
- appgw.ingress.kubernetes.io/health-probe-hostname
- appgw.ingress.kubernetes.io/health-probe-port
- appgw.ingress.kubernetes.io/health-probe-path
Those annotations allow user override health probe settings with values from annotations.
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1048
=> annotations: Expands list of health-probe related ingress annotations 

helm/ingress-azure/templates/clusterrole.yaml, helm/ingress-azure/templates/clusterrolebinding.yaml, vendor/modules.txt
rbac.authorization.k8s.io/v1alpha1 and rbac.authorization.k8s.io/v1beta1 API groups are deprecated in favor of rbac.authorization.k8s.io/v1, and will no longer be served in v1.20.
https://v1-17.docs.kubernetes.io/docs/setup/release/notes/
kubernetes/kubernetes#84758
This PR fix the usage of deprecated API groups
Closes #1074
=> helm: Moved RBAC from  v1beta1 to v1 (#1074)

pkg/k8scontext/ingress_handlers.go, pkg/k8scontext/ingress_handlers_test.go, pkg/k8scontext/secrets_handlers.go, pkg/k8scontext/secretstore.go
This PR fixes an issue in processing ingress event with TLS secret.
When ingress is processed, the referenced TLS secret is mapped to ingress and saved in a ingress-secret map.
In specific case where secret is malformed,, this step is skipped due to the `continue` statement. So later, when the certificate is fixed, it doesn't cause an event on AGIC and doesn't update the Application Gateway.
Secret is malformed in case customer is using a certificate manager which creates an empty secret initially and then fills the cert crt and key after generating them.
This is the place where secret handler checks if the secret is in the map or not.
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/6bc8764eb2ecff4a0c6ce96b9124ea36c7e4daa5/pkg/k8scontext/secrets_handlers.go#L55
Closes …
=> fix: update ingressSecretMap even when secret is malformed

helm/ingress-azure/values-template.yaml
… correctly
This is just a small correction so when the values.yaml artifact is generated from the values-template.yaml template we don't have problems on the chart.
As you can see, this chart was generated with the appgw property incorrectly: https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/ingress-azure-1.3.0-rc1.tgz
=> helm: Small adjustment in the values.yaml template to generate the artifact correctly

docs/setup/install-existing.md
Azure redirecting to different page. one less hop
=> docs: provide different link to create gateway instructions

pkg/azure/azure.go, pkg/azure/azure_test.go, pkg/azure/client.go
This PR prints operation ID of the PUT operation on Application Gateway to help with correlation.
```bash
I1203 15:20:25.617023    6292 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1203 15:20:28.763935    6292 client.go:201] OperationID='eb079ef6-5149-42fb-a2fe-93d4e27dd16b'
I1203 15:20:59.237489    6292 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1203 15:20:59.237578    6292 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1203 15:20:59.238658    6292 mutate_app_gateway.go:204] END AppGateway deployment
I1203 15:20:59.238741    6292 controller.go:151] Completed last event loop run in: 34.4547758s
```
=> debugging: print ARM operation ID to improve debugging

helm/ingress-azure/Chart.yaml, helm/ingress-azure/templates/deployment.yaml, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml
I am interested in a use-case where custom annotations are read from the resources. Currently this chart is lacking support for custom annotations fields.
I have updated the templates to allow setting `podAnnotations` field from the values file in order to add pod level annotations for this chart.
Update `values.yaml` to insert your custom annotations:
```
kubernetes:
podAnnotations: 
your.domain/cusom-annotations: important-value
```
This PR is addressing Issue #1083
=> feat: add support for custom annotations

docs/annotations.md
=> docs: add 'supported since' col in annotation table

functional_tests/duplicate_ports.json, functional_tests/health_probes_same_labels_different_namespaces.json, functional_tests/one_ingress_https_backend.json, functional_tests/one_ingress_https_backend_without_backend_protocol.json, functional_tests/one_ingress_slash_nothing.json, functional_tests/one_ingress_slash_slashnothing.json, functional_tests/one_ingress_with_multiple_path_rules.json, functional_tests/three_ingresses.json, functional_tests/two_ingresses_same_domain_tls_notls.json, functional_tests/two_ingresses_same_hostname_value_different_locations.json, functional_tests/two_ingresses_slash_slashsomething.json, functional_tests/two_ingresses_with_and_without_extended_hostname.json, functional_tests/waf_annotation.json, pkg/appgw/appgw_test.go, pkg/appgw/configbuilder.go, pkg/appgw/configbuilder_test.go
This PR removes the LastUpdatedByK8sIngress as this causes unnecessary in AppGW config and leads to longer to operation times.
=> config: remove tag LastUpdatedByK8sIngress as this causes diff in generated config

helm/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/fixtures/sample-config-empty.json, helm/ingress-azure/tests/fixtures/sample-config.json, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/aadpodidbinding.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/aadpodidentity.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/configmap.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/serviceaccount.yaml, helm/ingress-azure/values.yaml
This PR makes security context configurable through helm config. This was reported by a user who wanted to use AGIC without root permissions.
Fixes #1113
=> helm: optional host mounts with ability to run pod as non-root

deploy/azuredeploy.json
Version 1.18.14 is not available in some (maybe all) regions. Using the template throws error:
{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'ingress-appgw' is not valid according to the validation procedure. The tracking id is '3a051d9c-7a4e-4b1d-9d7b-44036d438f59'. See inner errors for details.","details":[{"code":"AgentPoolK8sVersionNotSupported","message":"Provisioning of resource(s) for container service aks1ab4 in resource group MyResourceGroup failed. Message: {\n  \"code\": \"AgentPoolK8sVersionNotSupported\",\n  \"message\": \"Version 1.18.14 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list\"\n }. …
=> Change default kubernetesVersion to 1.20.7

pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go
AGIC is hitting panic when processing url path maps with duplicate paths and ssl redirect annotation is true.
AGIC tries to print an error message using `BackendAddressPool.ID` which panics since path rule with redirect configuration doesn't have a backend pool.
```go
klog.Errorf("A path-rule with path '%s' already exists in config for BackendPool '%s'. Duplicate path-rule with BackendPool '%s' will not be applied.", path, *pathMap[path].BackendAddressPool.ID, *pathRule.BackendAddressPool.ID)
```
PANIC:
```
panic: runtime error: invalid memory address or nil pointer dereference …
```
=> fix: panic when processing duplicate paths in urlpathmap

pkg/azure/auth.go
* This issue is affecting AGIC addon in non-public cloud regions like China / US regions
* It affects addon when cluster is deployed in service principal mode.
* In this mode, AGIC uses the `clientId` and `clientSecret` fromm the cloud provider config.
* In this case, AGIC uses the standard `auth.NewClientCredentialsConfig` Auth library call which by default to public endpoints for AAD and ARM.
* This fails in non-public clouds.
In this fix, we use the `Cloud` name provided in the cloud provider config to initialize the correct endpoints.
This was tested in the mooncake AKS deployment.
Error without the fix:
After the fix, AGIC is able to successfully get a token and update AppGateway
=> fix: update AAD and Azure endpoints using Cloud from cpConfig

pkg/brownfield/brownfield_suite_test.go, pkg/brownfield/pathmaps.go, pkg/brownfield/routing_rules.go, pkg/brownfield/routing_rules_test.go, pkg/tests/fixtures/paths.go, pkg/tests/fixtures/paths_test.go
This PR fixes a bug in prohibited target.
When AGIC merges two routing rule together - existing and generated one - it also merged the attached URL path maps.
After merging AGIC deletes the second path map and only keeps the first one. This causes a bug when both first path map and second path map have the same `name`.
When path maps have the same name, they have already been merged when AGIC processes the path map before processing request routing rule. So, there is no need to merge the path maps again as it is already having the new rules.
Fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1257
=> fix(prohibited target): incorrect merge when rules being merged reference the same path map 

pkg/controller/prune.go, pkg/controller/prune_test.go, pkg/tests/fixtures/ingress.go
This fixes another old issue with prohibited target.
When AGIC processes the ingress objects, it prunes the rules/paths based on the prohibited target.
Since AGIC was modifying the ingress without making a `clone`, it was modify the original ingress which was taken from the k8s cache. This caused side effects when prohibited target was changed.
We now make a clone of the ingress before modifying it.
=> fix(prohibited target): modify cloned ingress instead of original ingress during pruning

docs/annotations.md, functional_tests/cookie_name.json, functional_tests/functional_test.go, pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/internaltypes.go
Generate a unique affinity cookie name when the annotation `cookie-based-affinity-distinct-name` is set to `true` in an ingress. This maintains affinity when using path based routing for different backends..
Adding the following annotations will ensure every backend has a different affinity cookie:
```yaml
appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
appgw.ingress.kubernetes.io/cookie-based-affinity-distinct-name: "true"
```
#772 Enhance annotation list of AGIC
=> Add cookie-based-affinity-distinct-name annotation

docs/annotations.md, pkg/annotations/ingress_annotations.go, pkg/appgw/identifier.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go
So that rewrite rule sets predefined in the app gateway can be assigned
to routing rules by adding an annotation in the corresponding Ingress.
Fixes #1003.
Related to #462.
=> rewrite: Add support for rewrite rule set assignment

helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml
In the helm\ingress-azure folder, where the helm value file resides, we noticed that the indentation for `ingressClass` is a bit off.
In the current master code, it is as if the  `ingressClass` is a standalone key in the value file, but after checking the code at this line of code: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/84e9ae00a2dc2e94f848b38cfee58e1d625c2463/helm/ingress-azure/templates/configmap.yaml#L92 
We figured out `ingressClass` should be the subkey of the `kubernetes`. We spent quite some time figuring this out and we hope it will not be the same trouble for others, thus motivating us to open this PR to fix this indentation error in the helm value files.
No issues found open
=> fix: indentation error in helm values file

deploy/azuredeploy.json, deploy/azuredeploywindowscluster.json, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
The two ARM templates `deploy/azuredeploy.json` and `deploy/azuredeploywindowscluster.json` were using old K8s versions that are not available in AKS anymore. 
```json
{
'code': 'InvalidTemplateDeployment', 
'message': "The template deployment 'ingress-appgw' is not valid according to the validation procedure. The tracking id is '251d5cab-xxxx-xxxx-xxxx-fd67a9731edf'. See inner errors for details."
}
Inner Errors:
{
'code': 'AgentPoolK8sVersionNotSupported', 
'message': 'Provisioning of resource(s) for container service aks6c30 in resourcegroup MyResourceGroup failed. Message: {\n  "code": "AgentPoolK8sVersionNotSupported",\n  "message": "Version 1.20.7 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more …
```
=> template: update aks default version in greenfield deploy templates

docs/setup/install-existing.md
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/crds/AzureIngressProhibitedTarget.yaml -> https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/crds/AzureIngressProhibitedTarget-v1-CRD-v1.yaml
Fixing broken link
=> doc: fixing broken link

pkg/k8scontext/supported_apiversion.go
Add retry logic and raise exception when there is issue getting server version of the cluster
#1342
=> k8s: Add retry logic to get server version

pkg/appgw/configbuilder.go, pkg/appgw/ingress_rules.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/tests/fixtures.go, scripts/e2e/cmd/runner/networking-v1-mfu_one_namespace_one_ingress_test.go, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-one-ingress/path-type/app.yaml
Ingress V1 adds a new property called pathType which is not currently by AGIC. This PR adds support for pathType while maintaining compatibility with cases where pathType is not specified.
https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
#1279
=> networking/v1: add support for ingress path type

docs/troubleshootings/troubleshooting-agic-addon-identity-not-found.md
- [n/a] If applicable, the changes made in the PR have proper test coverage
When running through these instructions, I found that the case for the `ingressApplicationGateway` addon profile was wrong.
Fixes the above docs.
=> Fix case on agicIdentity query

docs/helm-values-documenation.md, helm/ingress-azure/templates/deployment.yaml, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml
This surfaces some kubernetes configuration options through Helm to be able to run AGIC with `readOnlyRootFilesystem`. To make this work, the following new configuration options are exposed:
- Container `securityContext`
- Container `volumeMounts`
- Pod `volumes`
To run this now, one needs to add the following to the Helm `values.yaml`:
```yaml
kubernetes:
containerSecurityContext:
readOnlyRootFilesystem: true
volumes:
extraVolumes:
- name: tmp
emptyDir: {}
extraVolumeMounts:
- name: tmp
mountPath: /tmp
```
Fixes #1376
=> Add container securityContext and additional volumes to Helm chart

docs/features/appgw-ssl-certificate.md
I fixed the second script to get the principal id of the AGIC manage identity in the node resource group starting from the name and resource group of the AKS cluster.
=> Fixed the second script

pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go
This should fix a reported issue where AGICs were not checking
their name against the an ingress' class name.
#1422
=> Fix checking ingress class name

pkg/annotations/ingress_annotations.go, pkg/appgw/configbuilder.go, pkg/appgw/configbuilder_test.go, pkg/utils/retry_test.go, pkg/utils/threadsafemultimap_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This will prevent Application Gateway from rejecting a rule change
where a user has accidentally provided the same hostname twice in
an ingress hostname annotation.
This PR makes the AGIC ignore duplicate entries in an ingress hostnames annotation extension;
which would otherwise cause an error in the Application Gateway.
=> Drop duplicate hostnames from ingress hostname annotation

docs/examples/aspnetapp.yaml
the image location has changed. the old location no longer exists. I found this issue when referring to instructions on how to deploy a sample application here: https://learn.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing#deploy-a-sample-application-using-agic
the results can be verified using the following commands:
non-working location - 
docker pull mcr.microsoft.com/dotnet/core/samples:aspnetapp
working location - 
docker pull mcr.microsoft.com/dotnet/samples:aspnetapp
=> updating image location

docs/examples/aspnetapp.yaml, docs/features/appgw-ssl-certificate.md, docs/features/probes.md, docs/setup/install-new.md, docs/troubleshootings/troubleshooting-installing-a-simple-application.md, scripts/e2e/cmd/runner/testdata/extensions-v1beta1/one-namespace-many-ingresses/three-ingresses-slash-sth/app.yaml, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-many-ingresses/three-ingresses-slash-sth/app.yaml
Fix dotnet/samples:aspnetapp references
These files had references to the `mcr.microsoft.com/dotnet/core/samples` tag which is [no longer a supported tag](https://github.com/dotnet/dotnet-docker/blob/9eb203c4890d3d0122d3939614ff25d68fc46d6e/README.samples.md?plain=1#L93), and no longer exists.
This updates it to the supported tag: `mcr.microsoft.com/dotnet/samples:aspnetapp`
Without making these updates, the `aspnetapp` container used in the samples will be stuck in the `Pending` or `Waiting` state with reason `ImagePullBackOff` and an error: `Back-off pulling image "mcr.microsoft.com/dotnet/core/samples:aspnetapp"`
Related:
- https://github.com/dotnet/AspNetCore.Docs/pull/27202
- https://github.com/dotnet/dotnet-docker/discussions/3674
- …
=> Fix dotnet/samples:aspnetapp references

.pipelines/build.yml, Makefile, functional_tests/functional_test.go, functional_tests/rewrite_rule_sets_one_ingress_slash_slashnothing.json, pkg/apis/azureapplicationgatewayrewrite/v1beta1/types.go, pkg/appgw/rewrites.go, pkg/appgw/rewrites_test.go, pkg/k8scontext/secretstore_test.go, pkg/tests/fixtures.go
* This PR fixes an issue in the rewrite rule set feature in AGIC. AGIC is filling the URL configuration section in the Application Gateway's Rewrite even when the `rewrite` custom resource doesn't have that property specified. To fix this, we convert the url configuration to pointer reference instead an object reference. This way, if url configuration is not specified, we can just perform a `nil` check and not set the Application Gateway property.
* This PR also fixes an error in secret tests where pfx output size has changed. Most likely because of change in os version.
* Modifies the build pipeline to fix build issues.
Fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1496
=> fix: rewrite url config should be empty if not specified in the custom resource

Makefile, go.mod, go.sum, helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/templates/deployment.yaml, helm/ingress-azure/templates/serviceaccount.yaml, helm/ingress-azure/tests/fixtures/sample-config-workload-identity.json, helm/ingress-azure/tests/snapshots/sample-config-workload-identity/ingress-azure/templates/configmap.yaml, helm/ingress-azure/tests/snapshots/sample-config-workload-identity/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config-workload-identity/ingress-azure/templates/ingressclass.yaml, helm/ingress-azure/tests/snapshots/sample-config-workload-identity/ingress-azure/templates/serviceaccount.yaml, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml, pkg/azure/auth.go, pkg/azure/defaultazurecredential/authorizer.go
This PR adds support for workload identity in AGIC when installed via Helm. AGIC will use to communicate with ARM to update Application Gateway.
Feature Documentation: https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview
* updates the authorization code to use the latest `DefaultAzureCredentials` token provider which supports using workload identity.
* To use workload identity, type `workloadIdentity` will apply the required labels and annotations on Deployment and Service Account.
```yaml
armAuth:
type: workloadIdentity
identityClientID:  <>
```
* Label and Annotation on Service Account
*  Label on Pod
* Pod has required environment variables to enable workload identity
* AGIC successfully updating AppGW
Fixes https://github.com/Azure/application-gateway-kubernetes-ingre …
=> Support for workload identity in AGIC Helm installation

pkg/brownfield/targets.go, pkg/controller/helpers.go
use strings.EqualFold instead 
strings.EqualFold() Function in Golang reports whether s and t, interpreted as UTF-8 strings, are equal under Unicode case-folding, which is a more general form of case-insensitivity.
=> chore: use strings.EqualFold instead

pkg/azure/defaultazurecredential/authorizer.go, pkg/azure/defaultazurecredential/authorizer_test.go
This PR uses the `AZURE_ENVIRONMENT` to select the scope for fetching token.
=> Use cloud env variable to determine token scope

helm/ingress-azure/templates/crds.yaml
Add a missing quote for hostname when generating AzureIngressProhibitedTarget
Fixes #1548
=> Add missing quote for AzureIngressProhibitedTarget

functional_tests/helpers.go, helm/ingress-azure/tests/snapshots.go, pkg/appgw/appgw_test.go, pkg/azure/client_test.go, pkg/azure/cloudproviderconfig.go, pkg/k8scontext/secretstore.go, pkg/tests/fixtures.go, pkg/utils/utils.go
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
=> chore: remove refs to deprecated io/ioutil

docs/examples/aspnetapp.yaml
- [X ] The title of the PR is clear and informative
Tested with K8S version 1.26.6 on AKS, without ingressClassName spec pointing to IngressClass the AGIC does not seem to configure anything on ApplicationGateway. 
The default IngressClass is **azure-application-gateway** from **kubectl get IngressClass** command
The annotations are removed otherwise ingressClassName spec cannot be used.
=> Remove annotations and added ingressClassName spec

pkg/k8scontext/context.go, pkg/k8scontext/handlers_test.go, pkg/k8scontext/ingress_handlers_test.go, pkg/k8scontext/k8scontext_suite_test.go, pkg/k8scontext/k8scontext_test.go, pkg/k8scontext/secrets_handlers.go, pkg/k8scontext/secrets_handlers_test.go, pkg/k8scontext/secretstore.go, pkg/k8scontext/secretstore_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This PR attempts to fix condition where a certificate referenced by Ingress is not present in the local certificate cache by fetching the certificate from API server.
Right now, AGIC fails and creates a listener without HTTPS.
#1568
#1570
=> fix: get secret from cluster if not present in cache

.github/workflows/merge-build.yml
Successful run: https://github.com/Azure/application-gateway-kubernetes-ingress/actions/runs/9765432006
=> Migrate to github pipelines

cmd/appgw-ingress/main.go, cmd/appgw-ingress/utils.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go, pkg/appgw/health_probes.go, pkg/appgw/ingress_rules.go, pkg/appgw/istio_settings.go, pkg/appgw/requestroutingrules.go, pkg/azure/azure.go, pkg/azure/client.go, pkg/brownfield/health_probes.go, pkg/brownfield/http_settings.go, pkg/brownfield/listeners.go, pkg/brownfield/pathmaps.go, pkg/brownfield/pools.go, pkg/brownfield/redirects.go, pkg/brownfield/routing_rules.go, pkg/brownfield/targets.go, pkg/controller/controller.go, pkg/controller/mutate_aks.go, pkg/controller/mutate_app_gateway.go, pkg/controller/prune.go, pkg/controller/should_process.go, pkg/events/events.go, pkg/k8scontext/context.go, pkg/worker/worker.go, pkg/worker/worker_test.go
* This PR modifies the verbosity numbering from 5 to 3 for many log statements as 5 is also used by go-client and that causes a lot of noise in logging.
* This PR also prints when events are processed and skipped by AGIC. This is to help in debugging when AGIC doesn't perform actions.
```
I0712 15:48:50.613169   63055 worker.go:48] Skipping event. Reason: pod default/unrelated-55866f769d-8f92k is not used by any Ingress
I0712 15:49:03.618992   63055 worker.go:58] Processing k8s event of type:Update object:v1.Pod/default/related-5b79994554-tchxs
```
=> fix: adjust logging verbosity and event logs

cmd/appgw-ingress/main.go, cmd/appgw-ingress/utils.go, pkg/azure/client.go, pkg/cni/cni.go, pkg/cni/kubenet.go, pkg/cni/kubenet_test.go, pkg/cni/overlay.go, pkg/cni/overlay_test.go, pkg/controller/controller.go, pkg/controller/controller_test.go
This PR
* runs the CNI reconciler during the config building instead just during bootup. This enables supporting cluster upgrades.
* waits for OEC to reach terminal state before moving forward.
* re-creates OEC if subnet changes
=> Support overlay upgrades + wait for OEC to reach terminal state

cmd/appgw-ingress/main.go, helm/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-addon/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-existing-secret/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-workload-identity/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/cleanup-job.yaml, pkg/cni/cleanup.go, pkg/cni/cleanup_test.go
This PR moves the cleanup logic from directly using kubectl to moving it inside agic binary. This allows for more complicated cleanup logic which doesn't fail in non-overlay clusters.
=> Move overlay cleanup to code

Makefile
Updates the version of go used by `make build-image` and `make build-image-multi-arch` to the latest (1.24.4).
Patches some CVEs present in the current version of the Go stdlib being used.
=> Bumped the version of Go used in builds to 1.24.4
