Azure/application-gateway-kubernetes-ingress

CMakeLists.txt, pkg/appgw/appgw_suite_test.go, pkg/appgw/appgw_test.go
Have added tests for testing the generation of an application gateway configuration through the `ConfigBuilder` interface . In this commit we are testing only the HTTP ingress rules.
=> Added unit-test for the `appgw` package.

docs/tutorial.md
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/61
=> Installation link correction

docs/install-new.md
Update to docs to clarify which resource group should be targeted to obtain managed identity details
=> Update resource group reference

docs/install-existing.md
Now that RBAC can be TRUE or FALSE, update doc.
=> Remove description on RBAC=Fase

docs/install-existing.md
Set to manual scale instead of Auto Scale to avoid config errors from the service.
=> Inform to set to manual scale

deploy/azuredeploy.json
* Made the address space allocation for VNET, AKS subnet, etc .. to conform to a private address space.
* Bumped the AKS default version to a supported version.
=> Fixed deployment templates.

.gitignore, README.md, docs/annotations.md, pkg/annotations/ingress_annotations.go, pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/internaltypes.go, pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go
Introduced the backend prefix as an annotation.
Have run E2E tests with multiple ingress resources, to test the backend path prefix annotation.
=> Backend path prefix

pkg/appgw/appgw_test.go
Most tests in the application gateway package use the default backend HTTP settings, default backend pools and default listeners. Hence, re-wrote the tests so that we can use the defaults in most tests and override these defaults when required.
=> Re-organized the appgw tests in order to reduce duplication.

deploy/azuredeploy.json
This PR allows ability to select application gateway sku between Standard_v2 and WAF_v2.
WAF_v2 sku is configured with Detection mode.
In order to customize WAF, use azure portal or cli.
Fixes: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/102
=> Deployment Parameter for appgw sku

README.md
This reverts commit ad7695d75ddcc4c84d208569e9cb4ea81e5611db.
Reverting this commit due to broken links.
=> Revert "Mark preview features as preview"

go.mod, go.sum, pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go, vendor/github.com/deckarep/golang-set/.gitignore, vendor/github.com/deckarep/golang-set/.travis.yml, vendor/github.com/deckarep/golang-set/LICENSE, vendor/github.com/deckarep/golang-set/README.md, vendor/github.com/deckarep/golang-set/iterator.go, vendor/github.com/deckarep/golang-set/set.go, vendor/github.com/deckarep/golang-set/threadsafe.go, vendor/github.com/deckarep/golang-set/threadunsafe.go, vendor/modules.txt
This PR makes the cache store sync the pods and adds a function to filter pods with labels.
=> Cache pods and Pod Label filter

pkg/appgw/appgw_test.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/health_probes.go, pkg/appgw/identifier.go, pkg/appgw/internaltypes.go, pkg/controller/controller.go
This PR adds ability to provision health probes based on:
1) Readiness Probe
2) Liveness Probe
3) Backend Prefix
4) based on Path in the Ingress
5) Default Probe
=> Health Probes

pkg/appgw/test_fixtures.go
Adding more test fixtures to be used for testing Health Probes https://github.com/Azure/application-gateway-kubernetes-ingress/pull/158 and the SSL Redirect https://github.com/Azure/application-gateway-kubernetes-ingress/pull/156
=> tests: Augmenting test fixtures

pkg/appgw/appgw_test.go, pkg/appgw/health_probes.go
1) When service is removed by the user, It makes no sense to make a probe object. We will just reference the default probe.
2) Modified appgw_test to do the upper level testing for health probe.
=> health_probes: Handling service and Updating tests in appgw_tests

README.md
Adding the [Go Report Card](https://goreportcard.com/report/github.com/Azure/application-gateway-kubernetes-ingress) badge: 
[![Go Report Card](https://goreportcard.com/badge/Azure/application-gateway-kubernetes-ingress)](https://goreportcard.com/report/Azure/application-gateway-kubernetes-ingress)
=> Adding Go Report Card badge

pkg/annotations/ingress_annotations_test.go, pkg/appgw/appgw_test.go, pkg/appgw/frontend_listeners.go, pkg/appgw/identifier_test.go
Somehow some unfmted code snuck in.
Ran `go fmt $(go list ./... | grep -v /vendor/)`
=> go fmt everything

pkg/appgw/health_probes.go
With some more complex configuration we end up creating duplicate health probes.
This PR ensures that these are unique.
Also in this PR - removing `utils.UnorderedSet` and using `map`
Error message I ran into: 
```
W0528 18:07:24.518609   13094 controller.go:118] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"DuplicateResourceName","message":"Resource /subscriptions//resourceGroups//providers/Microsoft.Network/applicationGateways/ has two child resources with the same name (pb-websocket-service-80-websocket-ingress)."}]]
```
Ingress (deliberately reusing backend):
```yaml …
```
=> health_probes: Ensure unique names; Use map in lieu of UnorderedSet

pkg/appgw/backendhttpsettings.go
No functional code changes here;  Small tweak to make this a bit more readable; Prepare to remove the UnorderedSet / Insert idiom & swap w/ a map
=> BackendHTTPSettings: Create intermediate pair structs for clarity

pkg/appgw/backendhttpsettings.go, pkg/appgw/configbuilder.go, pkg/appgw/health_probes.go
Removing the use of UnorderedSets / ForEach semantic and using plain old Go maps.
=> health_probes: Remove ForEach

pkg/appgw/appgw_test.go
This PR checks that the new introduced annotations are set as expected.
=> annotations: test to check backend http annotation are set correctly

pkg/k8scontext/context.go
Tiny cleanup from a previous refactor
=> Refactor GetHTTPIngressList

cmd/appgw-ingress/main.go
It seems that `getEventRecorder` never really returns an error - so removing it.
On the other hand `os.Hostname()` does return an error, which I believe is non-Fatal and we could set a default since a) this should never happen in a controlled environment and b) the hostname is primarily used for logging purposes.
=> main: Tiny refactor

.env.example, .gitignore, docs/build.md, scripts/start.sh
I've been using this bash script to run the ingress on my dev box locally and connecting it to my AKS.
This might be helpful to other engineers.
=> Adding a runner script to scripts/start.sh; Update documentation

proposals/config_ownership_crd.md
Catching up the proposal with the already merged CRDs here: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/269
=> Rename ...Location to ...Target

cmd/appgw-ingress/main.go, pkg/annotations/ingress_annotations.go, pkg/appgw/appgw_test.go, pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go, pkg/k8scontext/types.go
This PR adds informers for Istio CRD and adds a IstioClient to the main function
=> Istio Ingress Informers 

pkg/appgw/types.go, pkg/controller/controller.go, pkg/k8scontext/context.go, pkg/k8scontext/types.go
Added a function to controller.go to log discovered Istio Gateways
=> log istio gateways

pkg/appgw/configbuilder.go
These comments are no longer correct.  Let's delete them.
=> Delete obsolete comments

pkg/appgw/backendaddresspools.go, pkg/appgw/backendhttpsettings.go, pkg/appgw/health_probes.go, pkg/appgw/requestroutingrules.go
This PR reorders some of the packages to position the main exported function at the top, the helpers after that.
There are no functional code changes here!
=> Reorder some packages so that the main function is at the top

pkg/appgw/requestroutingrules.go
This PR chops up `RequestRoutingRules` into smaller functions.
Out of `RequestRoutingRules` we carve out 2 new function:
- `getURLPathMaps`
- `getRules`
Also using this opportunity to simplify the creation of the `ApplicationGatewayRequestRoutingRule` object.
=> rules: Refactor into smaller functions

pkg/appgw/backendaddresspools.go
Refactoring `BackendAddressPools` in preparation for the larger PR for brownfield deployment.
This PR:
- removes `getBackendPoolMapValues`, which at this point seems like an overkill
- carves out `getPools` from `BackendAddressPools` so this block of code is easily reusable
=> BackendAddressPools: Refactor to simplify

go.mod, go.sum, pkg/controller/eventqueue.go, pkg/controller/helpers.go, pkg/utils/utils.go
This PR pretty-prints the events we receive from K8s so these are human-readable.
=> Verbosely log events

.pipelines/build.yml, .pipelines/merge-build.yml, .pipelines/release-build.yml, helm/release.sh
This PR breaks the build pipeline into two files.
`merge-build.yml` builds when there is PR/Merge on master branch.
`release-build.yml` builds and publishes artifacts when a tag is pushed. This in-turn triggers the release pipeline to create docker image and upload helm package to storage.
=> pipeline: added release pipeline and modifed release.sh

pkg/controller/helpers.go, pkg/utils/utils.go
This PR is a follow-up on https://github.com/Azure/application-gateway-kubernetes-ingress/pull/348#discussion_r300147734
=> Move SaveToFile to pkg/utils

pkg/appgw/types.go
Removing unnecessary package alias
=> Remove v1alpha3 alias

pkg/annotations/ingress_annotations.go, pkg/istio/controller/gateways.go, pkg/k8scontext/context.go
This PR adds an annotation to Istio Gateway to indicate that they should be handled by AGIC and creates a function to get all annotated gateways
=> Get annotated gateways

pkg/brownfield/pools_test.go, pkg/tests/fixtures/app_gateway.go, pkg/tests/fixtures/certificates.go, pkg/tests/fixtures/http_settings.go, pkg/tests/fixtures/listeners.go, pkg/tests/fixtures/paths.go, pkg/tests/fixtures/probes.go, pkg/tests/fixtures/routing_rules.go
Adding helpers that generate test fixtures for the brownfield deployment feature.
These are going to be used here: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/374
The bigger / entire picture is here: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/369
=> brownfield: Adding test fixtures

_config.yml, docs/.index, docs/annotations.md, docs/css/extra.css, docs/developers/build.md, docs/developers/contribute.md, docs/faq.md, docs/features.md, docs/features/multiple-namespaces.md, docs/features/private-ip.md, docs/features/probes.md, docs/how-to.md, docs/how-tos/helm-upgrade.md, docs/how-tos/lets-encrypt.md, docs/index.md, docs/setup/install-existing.md, docs/setup/install-new.md, docs/tutorial.md, mkdocs.yml
This PR used mkdocs to make a more structured webpage for AGIC.
=> docs: mkdocs based docs

README.md
This PR corrects some of the links and formatting in readme.
=> doc: readme corrections

pkg/appgw/backendhttpsettings.go
Sets up the basic structure to get the http settings from the virtual service
=> Istio HTTP Settings Set up

pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/http_listeners.go, pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go, pkg/brownfield/listeners.go
This PR code completes the listener section.
Merges uses the fact that a listener needs to have unique configuration of
1. port
1. ip
1. hostname
1. protocol
=> feat: [brownfield] listeners

pkg/k8scontext/context.go, pkg/k8scontext/types.go
No-op here. Simply renaming `AzureIngressProhibitedLocation` to `AzureIngressProhibitedTarget`
=> Rename AzureIngressProhibitedLocation --> AzureIngressProhibitedTarget

cmd/appgw-ingress/main.go, pkg/appgw/backendaddresspools.go, pkg/controller/helpers.go, pkg/controller/process.go
This PR slightly improves logging, by providing information on Namespaces and Blacklist when AGIC starts.
=> Improve logging

pkg/annotations/ingress_annotations.go, pkg/appgw/appgw_test.go, pkg/appgw/configbuilder.go, pkg/appgw/frontend_ipconfigurations.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/frontend_ports.go, pkg/appgw/ingress_rules.go, pkg/appgw/ingress_rules_test.go, pkg/appgw/internaltypes.go, pkg/appgw/redirects.go, pkg/appgw/redirects_test.go, pkg/appgw/requestroutingrules.go, pkg/appgw/test_fixtures.go, pkg/appgw/validators_test.go, pkg/controller/process.go, pkg/controller/prune.go, pkg/controller/prune_test.go, pkg/events/types.go, pkg/tests/fixtures.go, pkg/tests/fixtures/app_gateway.go, pkg/tests/fixtures/frontend_ipconfiguration.go
This PR adds prune function for prohibitedTarget and use Private IP.
=> feat: private ip annotation, prune function

.gitignore, .pipelines/build.yml, CMakeLists.txt, go.mod, go.sum
Augmenting our unit tests with code coverage stats collection.
Publishing the results to Azure DevOps.
=> ci: Run unit tests coverage; Publish results

docs/annotations.md, docs/features/private-ip.md
This PR adds documentation for use-private-ip annotation.
=> docs: use-private-ip annotation

pkg/k8scontext/context.go
This PR removes `func (i *InformerCollection) Run()` which seems to be unnecessary.
`func (i *InformerCollection) Run()` is here merged into `func (c *Context) Run()`
=> context: Simplify

pkg/appgw/requestroutingrules.go, pkg/appgw/requestroutingrules_test.go
This PR aims to simiplify url path map creation.
=> chore: refactor url path map generation

pkg/appgw/istio_pools.go, pkg/appgw/istio_virtual_service_rules.go, pkg/appgw/requestroutingrules.go
This PR defines some functions to help with Istio URL path maps and sets up the basic scaffolding in the requestroutingrules.go file
=> Istio Routing Rules Set Up

pkg/appgw/types.go, pkg/appgw/types_test.go, pkg/controller/helpers.go, pkg/controller/helpers_test.go, pkg/tests/fixtures.go
This is a small PR part of https://github.com/Azure/application-gateway-kubernetes-ingress/pull/335
=> ingressStatus: iningress list, parse resourceid, fixtures

pkg/appgw/appgw_test.go, pkg/appgw/backendaddresspools.go, pkg/appgw/backendaddresspools_test.go, pkg/appgw/istio_pools.go
This PR populates backend pool ID when a pool is created.
=> populate backendpool id

pkg/annotations/ingress_annotations.go, pkg/annotations/ingress_annotations_test.go
In this PR: 
- delete unused `IngressClass`
- fix `IsConnectionDraining`
- simplify
- tests
=> annotations: Fix bugs and test ingress annotations

pkg/appgw/appgw_test.go
This PR handles all potential errors that may have been returned from `Run`
=> tests: Capture and check errors in appgw tests

cmd/appgw-ingress/main.go
Break out when successfully able to get AppGw.
=> fix: return on no error in waitForArmAuth

pkg/appgw/backendaddresspools_test.go
This is merely stubbing out tests for our Istio components.
=> tests: Adding some Istio test stubs

pkg/appgw/appgw_test.go
No functional code changes in this PR.
=> Fixing a typo in unit tests

pkg/k8scontext/secretstore_test.go
Now that the Kubernetes Secret fixture is correct - we can reuse it
=> Simplify SecretStore test

pkg/appgw/appgw_test.go, pkg/appgw/configbuilder_test.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_listeners_test.go, pkg/appgw/public_and_private_ip_test.go, pkg/appgw/test_fixtures.go
This PR add support for `RequireServerNameIndication` field for V1 gateway.
This fields is needs to provide the correct certificate bound to the listener/hostname/port on V1.
=> Ensure SNI flag set on multi-site hostname listener (Azure#426)

pkg/azure/azure.go, pkg/azure/azure_test.go
This PR fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/510.
=> fix: ignore casing for MC prefix

docs/troubleshooting.md
Clarifying the 3 required Kubernetes resources.
=> documentation: improvement to the Troubleshooting section

cmd/appgw-ingress/errors.go, cmd/appgw-ingress/main.go
=> main: Adding error codes

pkg/azure/azure.go, pkg/azure/errors.go, pkg/controller/errors.go
Adding error codes to `controller` package
=> controller: Adding an error code

docs/troubleshooting.md
Adding more documentation on how to diagnose and troubleshoot AGIC
=> More troubleshooting

cmd/appgw-ingress/errors.go, cmd/appgw-ingress/main.go, cmd/appgw-ingress/main_test.go, helm/ingress-azure/templates/configmap.yaml, pkg/azure/auth.go, pkg/azure/azure_test.go, pkg/azure/client.go, pkg/azure/deploy.go, pkg/azure/errors.go, pkg/azure/fake.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/process.go, pkg/environment/environment.go, pkg/environment/environment_test.go
This PR adds ability to deploy AppGateway as a part of AGIC.
Will add more details here.
=> deploy: deploy AppGateway as part of AGIC start-up

cmd/appgw-ingress/errors.go, cmd/appgw-ingress/main.go, pkg/azure/auth.go, pkg/azure/client.go, pkg/environment/environment.go
This PR does the following:
1. fixes the notfound error
1. re-adds validate Env function
1. fixes deployment client to have authorizer
1. adds a flag for enabling AppGateway deployment
=> fix: notfound error, readd validate env, fix deploymentclient, flag

pkg/appgw/configbuilder.go
This reverts a PR :  Azure/application-gateway-kubernetes-ingress#577
=> Revert "Introducing removeOrphaned() func to ConfigBuilder"

pkg/azure/azure.go
Fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/598
=> log: change from Error to Warninig

docs/setup/install-new.md
Fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/594
=> fix: greenfield doc formatting

cmd/appgw-ingress/main.go, pkg/controller/controller.go, pkg/controller/process.go, pkg/controller/prune.go, pkg/events/types.go
This PR adds events that are emitted to AGIC pod for visibility. It only covers error in process and prune functions.
ConfigBuilder package remains.
=> events: emitting events to AGIC pod

helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/values.yaml, pkg/controller/process.go, pkg/environment/environment.go
This PR fixes helm and environment variable validations.
=> fix: helm and env validations

docs/setup/install-new.md
This PR makes it explicit that these command should be executed it Azure Cloud Shell.
Also provides an example for `deployment-outputs.json` to illustrate what the file contains.
=> Provide move documentation around deploying the ARM template w/ Azure Cloud Shell

docs/annotations.md, docs/setup/install-new.md
Added/fixed a couple things as per feedback from support.
=> Minor changes to annotations and install-new doc files

pkg/worker/worker.go
The goal of this proposal is to space out GET/PUT requests to ARM.
In this PR:
- adding `minTimeBetweenUpdates ` set to 1 second. This could also be a helm or environment variable
- the worker will measure the time between ARM PUT finished and when the next one would start and sleep for up to a second when it has been less than a second since the last update
Log:
```
I1030 17:08:17.321609   23454 worker.go:51] [worker] It has been 33µs since last update; Sleeping for 999.967ms before next update
```
=> Do not update ARM with a frequency higher than once a second

pkg/appgw/redirects.go
This PR fixes a SSL listener redirect scenario with shared app gateway.
When an AppGW already has an SSL listener and that listener is blacklisted, if we get an ingress that wants to share that listener, then we don't create a new listener for that hostname and use the already existing one. But we don't update the redirect configuration to now use the existing listener instead of the new one.
=> fix: perform listener lookup in redirect

docs/setup/install-new.md
Added note about rbac.enabled in helm.config
Fixed layout for helm.config variables
As a result of SR 119110422000482: AGW ingress controller is not healthy
=> Changes in install-new in section "Install Ingress Controller Helm Chart"

README.md, docs/how-tos/helm-upgrade.md
Small teaks to README to show latest version and a link to the GA announcement.
=> Add version badge + link to Ignite 2019 announcement

docs/setup/install-existing.md
=> doc: Correct principalId -> clientId

helm/ingress-azure/Chart.yaml, helm/ingress-azure/templates/configmap.yaml, helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml, pkg/azure/client.go
Fixes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/671
=> Adding option to select corect Cloud Environment endpoint

docs/how-tos/lets-encrypt.md
Update cert-manager to latest version v0.13.0
=> cert-manager v0.13.0

cmd/appgw-ingress/main.go, pkg/azure/client.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/environment/environment.go
Adding this variable to indicate if AGIC is hosted on underlay as master component.
=> env: add HOSTED_ON_UNDERLAY env variable

README.md, docs/how-tos/minimize-downtime-during-deployments.md, docs/zero-downtime-deployments.md
Adding a document outlining a method to decrease 502 errors during rolling updates.
=> doc: Zero downtime deployments document

docs/setup/install-existing.md
Helm no longer uses tiller, this seems to be no longer needed
=> helm no longer uses tiller (v3)

.pipelines/build.yml, .pipelines/release-build.yml
This PR allows to generate build artifacts for both merge and release builds.
=> build: generate build artifacts for both merge and release build

docs/setup/install-existing.md, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
This PR adds an explanation "use-private-ip" to the installation docs.
=> docs: add an explanation "use-private-ip"

docs/setup/install-existing.md, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
and set install command to helm3 syntax
=> Removed references to tiller

docs/features/agic-reconcile.md
Add scenario and instructions on how to use AGIC reconciler.
=> doc: add document for agic reconcile feature

docs/annotations.md
instructions and commands to use annotation appgw-trusted-root-certificate
=> doc: instructions on annotation appgw-trusted-root-certificate

docs/features/agic-reconcile.md, docs/features/appgw-ssl-certificate.md
feature includes appgw-ssl-certificate and reconciler
=> doc: update helm install/upgrade command with specific version

crds/AzureApplicationGatewayBackendPool_v1beta1.yaml
add azureapplicationgatewaybackendpool schema with api version of apiextensions.k8s.io/v1beta1
=> apiextensions.k8s.io/v1beta1 crd schema

docs/setup/install-existing.md, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
Fixes: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/836
=> doc: remove the aad pod identity master link from install instructions

helm/ingress-azure/templates/deployment.yaml
This PR adds a simple checksum in the deployment yaml. This will make sure that deployment is updated whenever there is change in helm values configuration.
For example, when the verbosity is changes, the configuration checksum will changes that will trigger a change in the deployment yaml.
`
checksum/config: a57ff98bfd2cc748f666131dd5538e513cdb744c4141baab3a9796c7c0b4d6db
`
=> helm: update deployment when config changes by using a checksum

functional_tests/functional_test.go, functional_tests/waf_annotation.json, pkg/appgw/ingress_rules.go, scripts/e2e/cmd/runner/testdata/one-namespace-one-ingress/ssl-e2e-redirect/app.yaml
This PR fixes a condition when determining whether to assign a waf policy to a listener.
=> fix: when path=('/', '/*', ''), set the waf policy to listener

docs/examples/sample-helm-config.yaml, docs/features/agic-reconcile.md, docs/helm-values-documenation.md, docs/helm.md
This PR adds a documentation around the supported fields in AGIC helm chart.
=> docs: add documentation around the supported fields in AGIC helm chart

docs/tutorial.md
As per https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/appgw/ingress_rules.go#L90 the tutorial had a false explanation/
- [n/a] If applicable, the changes made in the PR have proper test coverage
- [n/a] Issues addressed by the PR are mentioned in the description followed by `Fixes`.
From the source code:
Only associate the Listener with a Redirect if redirect is enabled
- clarified that in the doc.
No applicable Issue found.
=> Clarify what to do in order to create a HTTP Listener alongside a HTTPS Ingress

pkg/controller/should_process.go
Reduce the logging noise when no reconciling operation happens mostly
=> reduce agic reconciler logging noise

.pipelines/e2e-build.yml, .pipelines/merge-build.yml, .pipelines/nightly-build.yml, .pipelines/release-build.yml
=> e2e: trigger e2e to run nightly

CHANGELOG/CHANGELOG-1.2.md, docs/features/agic-reconcile.md, docs/features/appgw-ssl-certificate.md, docs/setup/install-existing.md, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
=> Add CHANGELOG for 1.2.0-rc3

docs/troubleshootings/README.md, docs/troubleshootings/troubleshooting-agic-addon-identity-not-found.md, docs/troubleshootings/troubleshooting-agic-fails-with-aad-pod-identity-breakingchange.md, docs/troubleshootings/troubleshooting-agic-pod-stuck-in-not-ready-state.md, docs/troubleshootings/troubleshooting-installing-a-simple-application.md
1. fix doc link
2. add table of list for troubleshooting guide
=> [Doc] Fix Doc Links

dockerfiles/deploy.Dockerfile
=> fix: use a non-root user

dockerfiles/deploy.Dockerfile
Introduce non-root user access to AGIC pod/container, update dockerfile to use non-root user
-  root user access to agic pod/container
=> use a non-root user

CHANGELOG/CHANGELOG-1.2.md, docs/setup/install-existing.md, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
=> changelog: update changelog for 1.2.1

cmd/appgw-ingress/main.go, helm/ingress-azure/templates/configmap.yaml, pkg/azure/client.go, pkg/azure/fake.go, pkg/environment/environment.go, pkg/environment/environment_test.go
As a user I want to select SKU of AGW. For now, all installations are using `Standard_v2` SKU because it is hardcoded.
None
=> Select AGW SKU via feature flag

dockerfiles/deploy.Dockerfile
[E2E run](https://dev.azure.com/azure/application-gateway-kubernetes-ingress/_releaseProgress?_a=release-environment-extension&releaseId=417&environmentId=911&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab)
=> dockerfile: update docker image to Ubuntu 20.04

scripts/e2e/cmd/runner/environment.go, scripts/e2e/cmd/runner/helper.go, scripts/e2e/cmd/runner/mfu_one_namespace_one_ingress_test.go, scripts/e2e/go.mod, scripts/e2e/go.sum, scripts/e2e/helper.sh, scripts/e2e/run-e2e.sh
=> e2e: add appgw client; move functions to helper.sh;

README.md
=> staging: add a nightly release badge

README.md, docs/developers/developer-guideline.md, docs/developers/nightly.md
=> nightly: add docs for nightly

CHANGELOG/CHANGELOG-1.2.md, CHANGELOG/CHANGELOG-1.3.md
=> changelog: add changelog for 1.3

helm/ingress-azure/templates/deployment.yaml
=> cherry-pick: fix security context (#1031)

README.md, docs/annotations.md
Usage of new annotation: appgw.ingress.kubernetes.io/override-frontend-port
=> [doc] annotation override-frontend-port usage

docs/features/custom-ingress-class.md, docs/helm-values-documenation.md
This PR adds documentation for ingress class feature.
Closes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1071
Closes https://github.com/Azure/application-gateway-kubernetes-ingress/issues/732
=> docs: ingressClass

docs/how-tos/networking.md
Parameters were created but not used.
=> docs: parameters fix

docs/setup/install-existing.md, docs/setup/install-new-windows-cluster.md, docs/setup/install-new.md
This PR changes the version to 1.3.0
=> docs: change 1.2.1 to 1.3.0

cmd/appgw-ingress/main.go, pkg/azure/client.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This PR adds a unique suffix to AGIC requests so that they can easily grouped together while debugging.
=> debug: add a unique agic identifier suffix to ARM user agent

helm/ingress-azure/values-template.yaml, helm/ingress-azure/values.yaml
=> helm: update helm values file

helm/ingress-azure/templates/deployment.yaml
=> fix: upgrade fail if security context is missing

docs/annotations.md, docs/helm-values-documenation.md
=> docs: update annotations versions and helm values doc

CHANGELOG/CHANGELOG-1.4.md
=> changelog: fix installation steps in changelog

scripts/e2e/run-e2e.sh
=> e2e: increase timeout to 120m

docs/annotations.md
=> Update annotations.md to fix typo

docs/features/appgw-ssl-certificate.md
Updated --out test.pfx to test-cert.pfx in openssl export step in order to be used in the following steps
=> Updated --out test.pfx to test-cert.pfx in docs/features/appgw-ssl-certificate.md

helm/ingress-azure/templates/clusterrole.yaml
Updates clusterrole yaml ingress API updates. was missed in previous PR
=> fix: update clusterrole yaml for v1 networking api

cmd/appgw-ingress/main.go, pkg/k8scontext/supported_apiversion.go
=> fix: correct version for ingress v1

crds/AzureApplicationGatewayLoadDistributionPolicy.yaml, crds/examples/AzureApplicationGatewayLoadDistributionPolicy.yaml, crds/examples/AzureApplicationGatewayLoadDistributionPolicy2.yaml
Adds minimum item requirement or LDP targets and fixes syntax in examples
=> (fix): Updates LDP crd definition and example yamls

docs/how-tos/continuous-deployment.md
Added the need to specify the Agent Specification, it would be helpful to specify explicitly this information.
=> doc: Update continuous-deployment.md

docs/annotations.md
- ✅ The title of the PR is clear and informative
- [-] If applicable, the changes made in the PR have proper test coverage
- [-] Issues addressed by the PR are mentioned in the description followed by `Fixes`.
Following an issue I had were my rewrites weren't working I found the issue was because I didn't have a /* in the path. Extending the documentation so others can find the same resolution quicker
=> Extending path rewrite documentation

.pipelines/build.yml, scripts/e2e/go.mod, scripts/e2e/go.sum
=> fix: update azure sdk version in e2e code

docs/features/appgw-ssl-certificate.md
Fix typo `Greenfeild` typo.
* None
=> Fix typo "Greenfeild"

docs/how-tos/networking.md
…plication Gateway and AKS" doc
This PR fixes the format of the broken `Future Readings` section and the list items in this doc [How to setup networking between Application Gateway and AKS](https://azure.github.io/application-gateway-kubernetes-ingress/how-tos/networking/)
=> Format `Future Readings` section in `How to setup networking between Application Gateway and AKS`

pkg/appgw/backendhttpsettings.go, pkg/appgw/backendhttpsettings_test.go, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-one-ingress/ssl-e2e-redirect/app.yaml
=> fix: port reference by name in ingress

.pipelines/build.yml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/aadpodidbinding.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/aadpodidentity.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/configmap.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/serviceaccount.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/aadpodidbinding.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/aadpodidentity.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/configmap.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/serviceaccount.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/aadpodidbinding.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/aadpodidentity.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/configmap.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/serviceaccount.yaml, scripts/e2e/cmd/runner/networking-v1-mfu_one_namespace_one_ingress_test.go, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-one-ingress/rewrite-rule/app.yaml
* This PR adds an e2e test for rewrite-rule set annotation. Application Gateway used with e2e has been updated with rewrite rule "test-rewrite-rule" that adds a response header "test-header: test-value".
* Generate helm yamls again due to an issue in helm version.
=> test: add e2e test for rewrite-rule-set annotation; fix helm test

docs/developers/build.md
replaced `<your-azure-resource-group>` with `<your-azure-subscription-id>` for the `subscriptionId` value description.
=> docs: fixed subscriptionId description

pkg/k8scontext/context.go, pkg/k8scontext/k8scontext_test.go
This PR fixes a panic when initializing informers.
IngressClass was being initialized even when cluster doesn't support v1/ingress
```
I0202 11:17:59.105168       1 utils.go:114] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14d360e]
goroutine 1 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.NewContext({_, _}, {_, _}, {_, _}, {_, _}, {0x2889330, 0x0, ...}, ...)
/azure/pkg/k8scontext/context.go:87 +0x76e
main.main()
/azure/cmd/appgw-ingress/main.go:103 +0x59c
```
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1333
=> fix: don't initialize ingress class when k8s doesn't support v1/ingress

CHANGELOG/CHANGELOG-1.5.md
=> docs: add changelog 1.5

docs/annotations.md
Replaces the last `extensions/v1beta1` with `networking.k8s.io/v1` in the docs.
N/A
=> docs: replace remaining `extensions/v1beta1` with `networking.k8s.io/v1` in docs

docs/.index, docs/ingress-v1.md
=> docs: add ingress v1 doc explaining AGIC implementation

docs/ingress-v1.md
added some more details and examples to document the pathtypes change in behavior
=> updated pathtypes documentation

docs/annotations.md
=> docs: add doc for hostname ext annotation

docs/annotations.md
=> docs: update annotation doc

docs/setup/install-new.md
=> Updating installation instructions

docs/tutorials/tutorial.general.md
These fields are required to pass the validation stage when
applying the yaml.
Fixes a small problem with the yaml in the guest (general) tutorial.
I imagine these fields became mandatory at some point after the tutorial was written.
=> Add path and pathType to guestbook tutorial yaml

.pipelines/build.yml, .pipelines/nightly-build.yml, .pipelines/release-build.yml
=> Fix for e2e tests

helm/ingress-azure/crds/azureapplicationgatewayrewrite.yaml, pkg/annotations/ingress_annotations_test.go, pkg/appgw/health_probes.go, scripts/e2e/cmd/runner/helper.go, scripts/e2e/cmd/runner/networking-v1-mfu_one_namespace_one_ingress_test.go, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-one-ingress/ingress-class-resource/other-ingress-class.yaml
This PR does the following:
1. Add rewrite crd to helm
2. Add tests for BackendProtocol
3. Fix probe protocol selection logic by correctly resolving service port.
4. Fix ingress class e2e
=> add rewrite crd to helm; add tests for BackendProtocol; fix probe protocol selection logic; fix ingress class e2e

docs/examples/sample-app/README.md, docs/examples/sample-app/deployment.yaml, docs/examples/sample-app/ingress-http.yaml, docs/examples/sample-app/ingress-https.yaml
=> Fix sample app tutorial artefacts 

go.mod, go.sum, pkg/environment/fake.go, pkg/k8scontext/context.go, pkg/k8scontext/ingress_handlers_test.go, pkg/tests/fixtures.go, scripts/e2e/cmd/runner/networking-v1-ingress_class_test.go, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-one-ingress/ssl-e2e-redirect/app.yaml
=> fix: get ingress class from client if not found in cache

helm/ingress-azure/tests/fixtures/sample-config.json, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/deployment.yaml, scripts/e2e/cmd/runner/helper.go, scripts/e2e/cmd/runner/networking-v1-ingress_class_test.go, scripts/e2e/cmd/runner/networking-v1-mfu_one_namespace_one_ingress_test.go, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-one-ingress/ssl-profile/app.yaml
=> test: render test for security context; e2e for ssl profile; move ingress class e2e

helm/ingress-azure/Chart.yaml, helm/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/configmap.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/serviceaccount.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/configmap.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/serviceaccount.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/configmap.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/deployment.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/serviceaccount.yaml, helm/ingress-azure/values.yaml
=> check volumes in deployment.yaml; fix version;

scripts/e2e/cmd/runner/extensions-v1beta-ingress_class_test.go, scripts/e2e/cmd/runner/extensions-v1beta1-lfu_one_namespace_one_ingress_test.go, scripts/e2e/cmd/runner/extensions-v1beta1-mfu_one_namespace_many_ingresses_test.go, scripts/e2e/cmd/runner/extensions-v1beta1-mfu_one_namespace_one_ingress_test.go
=> modify build tag to e2eextensionv1beta1 for old tests

docs/how-tos/minimize-downtime-during-deployments.md
Fix the markdown formatting the the "minimize downtime" docs so that it renders correctly at https://azure.github.io/application-gateway-kubernetes-ingress/how-tos/minimize-downtime-during-deployments/.
=> Fix formatting in "minimize downtime" docs

pkg/azure/client.go
=> fix: increase arm client operation polling interval

Makefile, go.mod, go.sum, pkg/azure/client.go, pkg/k8scontext/secretstore_test.go
=> increase polling interval

scripts/e2e/cmd/runner/networking-v1-mfu_one_namespace_many_ingresses_test.go, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-many-ingresses/hostname-with-wildcard-priority/app.yaml
=> e2e: fix for rule priority test

CHANGELOG/CHANGELOG-1.6.md, CHANGELOG/CHANGELOG-1.7.md
=> add changelog for 1.7

docs/how-tos/minimize-downtime-during-deployments.md
c is for cookie and cookie is for me
=> doc: casing fix

docs/features/custom-ingress-class.md
Custom ingress class tutorial updates
Custom ingress class should no longer use annotations
Remove annotations and replace with CRD
YAML formatting
=> Custom ingress class updates

pkg/appgw/configbuilder.go, pkg/appgw/frontend_listeners.go, pkg/appgw/frontend_listeners_istio.go, scripts/e2e/cmd/runner/helper.go, scripts/e2e/cmd/runner/networking-v1-mfu_one_namespace_many_ingresses_test.go, scripts/e2e/cmd/runner/testdata/networking-v1/one-namespace-many-ingresses/same-port-public-private/app.yaml
This PR removes restriction on using same port on both public and private ingresses.
=> allow same port to used on both public and private ingresses

Makefile, cmd/appgw-ingress/main.go, go.mod, pkg/azure/auth.go, pkg/azure/auth_test.go, pkg/azure/azure_suite_test.go, pkg/azure/azure_test.go, pkg/azure/client.go, pkg/azure/client_test.go, pkg/azure/fake.go
https://github.com/Azure/application-gateway-kubernetes-ingress/pull/1435
=> Authorizer Retry Bug Fix  (#1435)

pkg/azure/client.go
=> Fix typo in response message

pkg/azure/defaultazurecredential/authorizer.go, pkg/azure/defaultazurecredential/authorizer_test.go
=> Use cloud env variable to determine token scope (#1563)

docs/how-tos/deploy-AGIC-with-Workload-Identity-using-helm.md
=> Add docs for workload identity

docs/examples/aspnetapp.yaml
The image uses 8080 port internally, so changed the service and pod like that
=> The image uses 8080 port internally, so changed the service and pod like that

pkg/k8scontext/context.go, pkg/k8scontext/handlers_test.go, pkg/k8scontext/ingress_handlers_test.go, pkg/k8scontext/k8scontext_suite_test.go, pkg/k8scontext/k8scontext_test.go, pkg/k8scontext/secrets_handlers.go, pkg/k8scontext/secrets_handlers_test.go, pkg/k8scontext/secretstore.go, pkg/k8scontext/secretstore_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
* fix: get secret from cluster if not present in cache
* if not present on apiserver, return nil
=> fix: get secret from cluster if not present in cache (#1571)

.pipelines/merge-build.yml
=> Migrate to just GH Action 

Dockerfile, Makefile, scripts/release-helm.sh, scripts/release-image.sh
This PR adds publish scripts for helm and images. It also fixes the base image version for the docker container used to run the binary.
=> Add publish script for helm and images; upgrade binary image to ubuntu 22.04

deploy/azuredeploy.json
Bump to default version
Bumps AKS version to a move recent version
=> Use deployment to reflect latest aks version

.github/dependabot.yml, .github/workflows/merge-build.yml, .github/workflows/vuln-scanner.yml, Dockerfile, Makefile, scripts/release-helm.sh, scripts/release-image.sh
This PR adds
* run trivy scan periodically and during merges. It also integrates with github security tab, such that vuln. shows on the tab.
* make command to simplify the release process.
=> Run vulnerability scanner periodically; simplify release commands

.github/workflows/merge-build.yml, .github/workflows/vuln-scanner.yml, Makefile, helm/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-addon/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-empty/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-existing-secret/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-prohibited-target/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config-workload-identity/ingress-azure/templates/cleanup-job.yaml, helm/ingress-azure/tests/snapshots/sample-config/ingress-azure/templates/cleanup-job.yaml
=> fix: fix label and add render chart command

.github/workflows/vuln-scanner.yml, Makefile
=> fix: go version and pipeline fix

pkg/azure/client.go
Create and update agic managed application gateway subnet with delegation property
Test Verified:
1. Provision a new subnet with delegation by agic
2. Provision a new subnet without delegation by agic
3. Backfill the subnet (step2) with deegation by agic
Support subnet delegation for private-only AGIC managed AppGw
=> AppGw Subnet Delegation Support

CHANGELOG/CHANGELOG-1.8.md
=> 1.8 Changelog

go.mod, scripts/e2e/go.mod
This is to satisfy a vuln scan that flagging an issue with JWT although I don't believe the relevant function is being used.
=> Bumped JWT version

CHANGELOG/CHANGELOG-1.8.md
=> Changelog for 1.8.1

go.mod
=> Bumped jwt version (again)

docs/annotations.md, docs/features/custom-ingress-class.md, docs/features/rewrite-rule-set-custom-resource.md, docs/how-tos/dns.md
Removes namespace from example to help with deployments made via add-on.
=> Remove namespace from example

docs/.index, docs/developers/build.md, docs/developers/design.md, docs/features/appgw-ssl-certificate.md, docs/features/custom-ingress-class.md, docs/setup/install.md
=> Fixed broken links in GH pages docs
